# Terragrunt Built-in Functions

In [142]:
from os.path import join
from requests import get
from bs4 import BeautifulSoup
from copy import deepcopy
import re
import pandas as pd

BASE = "https://terragrunt.gruntwork.io"
REPO_ABSPATH = "/utkusarioglu-com/workshops/backtesting-workshop"
ARTIFACTS_SUBPATH = "artifacts/terragrunt"
url = f"{BASE}/docs/reference/built-in-functions"
artifacts_abspath = join(REPO_ABSPATH, ARTIFACTS_SUBPATH)
artifact_html_abspath = join(artifacts_abspath, "built_in_functions.html")
artifact_csv_abspath = join(artifacts_abspath, "built_in_functions.csv")

In [82]:
# Fetch and store html artifact
def fetch_and_store():
    response = get(url)
    if response.status_code != 200:
        raise RuntimeError("FETCH_UNSUCCESSFUL")
    html = open(artifact_html_abspath, "w+")
    html.write(response.text)
    html.close()


# fetch_and_store()

In [90]:
cache = open(artifact_html_abspath, "r")
html = cache.read()
cache.close()
soup = BeautifulSoup(html)
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,700" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Fira+Mono&amp;display=swap" rel="stylesheet"/>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="/assets/css/prism.css" rel="stylesheet"/>
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<title>Built-in functions</title>
<meta content="Terragrunt allows you to use built-in functions anywhere in `terragrunt.hcl`, just like Terraform." name="description"/>
<link href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/
" rel="canonical"/>
<meta content="index" name="robots"/>
<link href="/assets/css/styles.css" rel="stylesheet">
<link href="/assets/img/favicon/favicon.ico" rel="icon" type="image/x-icon"/>
<link href="/assets/img/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/assets/img/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/assets/img/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/assets/img/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/assets/img/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/assets/img/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/assets/img/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/assets/img/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/assets/img/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/assets/img/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/assets/img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/assets/img/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/assets/img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/assets/img/favicon/manifest.json" rel="manifest"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/assets/img/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<meta content="#161d25" name="background-color"/>
<meta content="summary" name="twitter:card">
<meta content="" name="twitter:site">
<meta content="Built-in functions" name="twitter:title">
<meta content="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/
" name="twitter:url">
<meta content="Terragrunt allows you to use built-in functions anywhere in `terragrunt.hcl`, just like Terraform." name="twitter:description">
<meta content="https://terragrunt.gruntwork.io/assets/img/terragrunt-thumbnail.png" name="twitter:image">
<meta content="Built-in functions" property="og:title">
<meta content="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/
" property="og:url">
<meta content="Terragrunt | Terraform wrapper" property="og:site_name">
<meta content="" property="article:author"/>
<meta content="Terragrunt allows you to use built-in functions anywhere in `terragrunt.hcl`, just like Terraform." property="og:description"/>
<meta content="https://terragrunt.gruntwork.io/assets/img/terragrunt-thumbnail.png" property="og:image"/>
</meta></meta></meta></meta></meta></meta></meta></meta></meta></link></head>
<body class="built-in-functions collection-browser collection-browser-doc subpage">
<div class="subpage__header subpage__header--min section-colorful-bg">
<header class="header">
<nav class="navbar navbar-default">
<div class="container-fluid">
<div class="navbar-header">
<button aria-expanded="false" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-2" data-toggle="collapse" type="button">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<div class="navbar-brand navbar-brand-beta">
<div class="terragrunt-logo">
<a class="logo-terragrunt" href="/">Terragrunt</a>
<a class="gruntwork" href="https://gruntwork.io/" target="_blank">by <strong>Gruntwork.io</strong></a>
</div>
</div>
</div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
<ul class="nav navbar-nav navbar-right">
<li><a href="https://gruntwork.io/careers"><span class="new-label">NEW</span>We're Hiring!</a></li>
<li><a ga-event-action="install-terragrunt" ga-event-category="nav-docs-04-reference-built-in-functions-md" ga-on="click" href="/docs/getting-started/install">Install</a></li>
<li><a ga-event-action="quick-start" ga-event-category="nav-docs-04-reference-built-in-functions-md" ga-on="click" href="/docs/getting-started/quick-start">Quick Start</a></li>
<li><a ga-event-action="docs" ga-event-category="nav-docs-04-reference-built-in-functions-md" ga-on="click" href="/docs/">Docs</a></li>
<li><a ga-event-action="use-cases" ga-event-category="nav-docs-04-reference-built-in-functions-md" ga-on="click" href="/docs/#features">Use cases</a></li>
<li>
<a class="github-nav-link" ga-event-action="github" ga-event-category="nav-github" ga-on="click" href="https://github.com/gruntwork-io/terragrunt">
<img alt="GitHub" src="/assets/img/logos/github-logo.png"/>
</a>
</li>
</ul>
</div>
</div>
</nav>
</header>
<div class="header-bg">
<div class="overflow-hide">
<img alt="Shape" class="header-shapes-top" src="/assets/img/home/t-o-1@3x.png"/>
</div>
<img alt="Shape" class="header-shapes-hero" src="/assets/img/home/top_left.svg"/>
</div>
</div>
<div class="cb-doc-detail">
<div class="container-fluid">
<div class="row">
<div class="col-xs-12">
<div class="cb-doc-header">
<ol class="breadcrumb text-center">
<a ga-event-action="docs-main-index" ga-event-category="docs-built-in-functions" ga-on="click" href="/docs">Docs</a>
<a ga-event-action="docs-breadcrumb-reference" ga-event-category="docs-built-in-functions" ga-on="click" href="/docs#reference">/ <span>Reference</span></a>
<a href="#"> / <span> Built in functions</span></a>
</ol>
<div class="cb-doc-title text-center">
<h1>Built-in functions</h1>
<span class="badge badge-pill badge-default">

          Functions
        </span>
</div>
</div>
</div>
</div>
</div>
<div class="container-cb-lg">
<div class="row equal">
<div class="col-md-2-5">
<div class="cb-doc-sidebar js-scroll-with-user" data-nav-current-cat="reference" data-nav-current-page="built-in-functions" data-scroll-after-selector=".cb-doc-header" data-scroll-until-selector=".cb-doc-detail" id="toc">
<div class="toc-toggle visible-xs visible-sm">
<button class="toc-toggle__button" id="toc-toggle-open"><span class="glyphicon glyphicon-menu-hamburger"></span></button>
<button class="toc-toggle__button" id="toc-toggle-close"><span class="glyphicon glyphicon-remove"></span></button>
</div>
<div class="nav-doc-collection-link">
<a href="/docs/"><span class="glyphicon glyphicon-share-alt icon-flipped"></span> Documentation</a>
</div>
<ul>
<li><span aria-controls="docs-getting-started" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-docs-getting-started" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs#getting-started">Getting started</a>
<ul>
<li><span aria-controls="quick-start-getting-started" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-quick-start-getting-started" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/quick-start/">Quick start</a>
<ul>
<li><span aria-controls="quick-start-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-quick-start-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/quick-start/#introduction">Introduction</a></li>
<li><span aria-controls="quick-start-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-quick-start-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/quick-start/#example">Example</a>
<ul>
<li><span aria-controls="quick-start-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-quick-start-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/quick-start/#terragrunthcl">terragrunt.hcl</a></li>
</ul>
</li>
<li><span aria-controls="quick-start-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-quick-start-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/quick-start/#key-features">Key features</a>
<ul>
<li><span aria-controls="quick-start-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-quick-start-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/quick-start/#keep-your-backend-configuration-dry">Keep your backend configuration DRY</a></li>
<li><span aria-controls="quick-start-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-quick-start-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/quick-start/#keep-your-provider-configuration-dry">Keep your provider configuration DRY</a></li>
<li><span aria-controls="quick-start-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-quick-start-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/quick-start/#keep-your-terraform-cli-arguments-dry">Keep your Terraform CLI arguments DRY</a></li>
<li><span aria-controls="quick-start-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-quick-start-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/quick-start/#promote-immutable-versioned-opentofuterraform-modules-across-environments">Promote immutable, versioned OpenTofu/Terraform modules across environments</a></li>
</ul>
</li>
<li><span aria-controls="quick-start-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-quick-start-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/quick-start/#next-steps">Next steps</a></li>
</ul>
</li>
<li><span aria-controls="install-getting-started" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-install-getting-started" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/install/">Install</a>
<ul>
<li><span aria-controls="install-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-install-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/install/#install-terragrunt">Install Terragrunt</a>
<ul>
<li><span aria-controls="install-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-install-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/install/#download-from-releases-page">Download from releases page</a></li>
<li><span aria-controls="install-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-install-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/install/#install-via-a-package-manager">Install via a package manager</a></li>
<li><span aria-controls="install-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-install-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/install/#enable-tab-completion">Enable tab completion</a></li>
<li><span aria-controls="install-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-install-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/install/#terragrunt-github-action">Terragrunt GitHub Action</a></li>
</ul>
</li>
</ul>
</li>
<li><span aria-controls="terraform-and-opentofu-version-compatibility-table-getting-started" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-terraform-and-opentofu-version-compatibility-table-getting-started" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/supported-versions/">Terraform and OpenTofu Version Compatibility Table</a>
<ul>
<li><span aria-controls="terraform-and-opentofu-version-compatibility-table-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-terraform-and-opentofu-version-compatibility-table-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/supported-versions/#supported-opentofu-versions">Supported OpenTofu Versions</a></li>
<li><span aria-controls="terraform-and-opentofu-version-compatibility-table-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-terraform-and-opentofu-version-compatibility-table-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/supported-versions/#supported-terraform-versions">Supported Terraform Versions</a></li>
</ul>
</li>
<li><span aria-controls="configuration-getting-started" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-configuration-getting-started" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/configuration/">Configuration</a>
<ul>
<li><span aria-controls="configuration-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-configuration-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/configuration/#terragrunt-configuration-file">Terragrunt configuration file</a></li>
<li><span aria-controls="configuration-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-configuration-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/configuration/#configuration-parsing-order">Configuration parsing order</a></li>
<li><span aria-controls="configuration-getting-started-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-configuration-getting-started-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/getting-started/configuration/#formatting-hcl-files">Formatting hcl files</a></li>
</ul>
</li>
</ul>
</li>
<li><span aria-controls="docs-features" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-docs-features" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs#features">Features</a>
<ul>
<li><span aria-controls="keep-your-terraform-code-dry-features" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-keep-your-terraform-code-dry-features" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/features/keep-your-terraform-code-dry/">Keep your Terraform code DRY</a>
<ul>
<li><span aria-controls="keep-your-terraform-code-dry-features-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-keep-your-terraform-code-dry-features-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/features/keep-your-terraform-code-dry/#keep-your-terraform-code-dry">Keep your Terraform code DRY</a>
<ul>
<li><span aria-controls="keep-your-terraform-code-dry-features-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-keep-your-terraform-code-dry-features-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/features/keep-your-terraform-code-dry/#motivation">Motivation</a></li>
<li><span aria-controls="keep-your-terraform-code-dry-features-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-keep-your-terraform-code-dry-features-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/features/keep-your-terraform-code-dry/#remote-terraform-configurations">Remote Terraform configurations</a></li>
<li><span aria-controls="keep-your-terraform-code-dry-features-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-keep-your-terraform-code-dry-features-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>
</span><a href="/docs/features/keep-your-terraform-code-dry/#achieve-dry-terraform-code-and-immutable-infrastructure">Achieve DRY Terraform code and immutable infrastructure</a></li>
<li><span aria-controls="keep-your-terraform-code-dry-features-" aria-expanded="false" class="nav-collapse-handler category-head collapsed" data-toggle="collapse" id="cat-nav-id-keep-your-terraform-code-dry-features-" role="button">
<span class="arrow-icon glyphicon glyphicon-triangle-bottom"></span>

### Find article

In [91]:
article = soup.find(class_="cb-doc-content js-scroll-spy")
article

<div class="cb-doc-content js-scroll-spy" data-scroll-spy-nav-selector="#toc">
<p>Terragrunt allows you to use built-in functions anywhere in <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code>, just like Terraform! The functions currently available are:</p>
<ul>
<li><a href="#terraform-built-in-functions">Terraform built-in functions</a></li>
<li><a href="#find_in_parent_folders">find_in_parent_folders</a></li>
<li><a href="#path_relative_to_include">path_relative_to_include</a></li>
<li><a href="#path_relative_from_include">path_relative_from_include</a></li>
<li><a href="#get_env">get_env</a></li>
<li><a href="#get_platform">get_platform</a></li>
<li><a href="#get_repo_root">get_repo_root</a></li>
<li><a href="#get_path_from_repo_root">get_path_from_repo_root</a></li>
<li><a href="#get_path_to_repo_root">get_path_to_repo_root</a></li>
<li><a href="#get_terragrunt_dir">get_terragrunt_dir</a></li>
<li><a href="#get_working_dir">get_working_dir</a></li>
<li><a href="#get_parent_terragrunt_dir">get_parent_terragrunt_dir</a></li>
<li><a href="#get_original_terragrunt_dir">get_original_terragrunt_dir</a></li>
<li><a href="#get_terraform_commands_that_need_vars">get_terraform_commands_that_need_vars</a></li>
<li><a href="#get_terraform_commands_that_need_input">get_terraform_commands_that_need_input</a></li>
<li><a href="#get_terraform_commands_that_need_locking">get_terraform_commands_that_need_locking</a></li>
<li><a href="#get_terraform_commands_that_need_parallelism">get_terraform_commands_that_need_parallelism</a></li>
<li><a href="#get_aws_account_id">get_aws_account_id</a></li>
<li><a href="#get_aws_caller_identity_arn">get_aws_caller_identity_arn</a></li>
<li><a href="#get_terraform_command">get_terraform_command</a></li>
<li><a href="#get_terraform_cli_args">get_terraform_cli_args</a></li>
<li><a href="#get_default_retryable_errors">get_default_retryable_errors</a></li>
<li><a href="#get_aws_caller_identity_user_id">get_aws_caller_identity_user_id</a></li>
<li><a href="#run_cmd">run_cmd</a></li>
<li><a href="#read_terragrunt_config">read_terragrunt_config</a></li>
<li><a href="#sops_decrypt_file">sops_decrypt_file</a></li>
<li><a href="#get_terragrunt_source_cli_flag">get_terragrunt_source_cli_flag</a></li>
<li><a href="#read_tfvars_file">read_tfvars_file</a></li>
</ul>
<h2 id="terraform-built-in-functions">Terraform built-in functions</h2>
<p>All <a href="https://www.terraform.io/docs/configuration/functions.html">Terraform built-in functions</a> are supported in Terragrunt config files:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">terraform</span> <span class="p">{</span>
  <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${basename(get_terragrunt_dir())}"</span>
<span class="p">}</span>

<span class="nx">remote_state</span> <span class="p">{</span>
  <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>
  <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>
    <span class="nx">bucket</span> <span class="p">=</span> <span class="nx">trimspace</span><span class="err">(</span><span class="s2">"   my-terraform-bucket     "</span><span class="err">)</span>
    <span class="nx">region</span> <span class="p">=</span> <span class="nx">join</span><span class="err">(</span><span class="s2">"-"</span><span class="err">,</span> <span class="p">[</span><span class="s2">"us"</span><span class="p">,</span> <span class="s2">"east"</span><span class="p">,</span> <span class="s2">"1"</span><span class="p">]</span><span class="err">)</span>
    <span class="nx">key</span>    <span class="p">=</span> <span class="nx">format</span><span class="err">(</span><span class="s2">"%s/terraform.tfstate"</span><span class="err">,</span> <span class="nx">path_relative_to_include</span><span class="err">())</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre></div></div>
<p>Note: Any <code class="language-plaintext highlighter-rouge">file*</code> functions (<code class="language-plaintext highlighter-rouge">file</code>, <code class="language-plaintext highlighter-rouge">fileexists</code>, <code class="language-plaintext highlighter-rouge">filebase64</code>, etc) are relative to the directory containing the <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file they’re used in.</p>
<p>Given the following structure:</p>
<pre><code class="language-tree">└── terragrunt
  └── common.tfvars
  ├── assets
  |  └── mysql
  |     └── assets.txt
  └── terragrunt.hcl
</code></pre>
<p>Then <code class="language-plaintext highlighter-rouge">assets.txt</code> could be read with the following function call:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">file</span><span class="err">(</span><span class="s2">"assets/mysql/assets.txt"</span><span class="err">)</span>
</code></pre></div></div>
<h2 id="find_in_parent_folders">find_in_parent_folders</h2>
<p><code class="language-plaintext highlighter-rouge">find_in_parent_folders()</code> searches up the directory tree from the current <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file and returns the absolute path to the first <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> in a parent folder or exit with an error if no such file is found. This is primarily useful in an <code class="language-plaintext highlighter-rouge">include</code> block to automatically find the path to a parent <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The function takes an optional <code class="language-plaintext highlighter-rouge">name</code> parameter that allows you to specify a different path to search for:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-other-file-name.hcl"</span><span class="err">)</span>
<span class="p">}</span>
</code></pre></div></div>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-folder"</span><span class="err">)</span>
<span class="p">}</span>
</code></pre></div></div>
<p>You can also pass an optional second <code class="language-plaintext highlighter-rouge">fallback</code> parameter which causes the function to return the fallback value (instead of exiting with an error) if the file in the <code class="language-plaintext highlighter-rouge">name</code> parameter cannot be found:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-other-file-name.hcl"</span><span class="err">,</span> <span class="s2">"fallback.hcl"</span><span class="err">)</span>
<span class="p">}</span>
</code></pre></div></div>
<p>Note that this function searches relative to the child <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file when called from a parent config. For
example, if you had the following folder structure:</p>
<pre><code class="language-tree">    ├── terragrunt.hcl
    └── prod
        ├── env.hcl
        └── mysql
            └── terragrunt.hcl
</code></pre>
<p>And the root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> contained the following:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">locals</span> <span class="p">{</span>
  <span class="nx">env_vars</span> <span class="p">=</span> <span class="nx">read_terragrunt_config</span><span class="err">(</span><span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"env.hcl"</span><span class="err">))</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The <code class="language-plaintext highlighter-rouge">find_in_parent_folders</code> will search from the <strong>child <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code></strong> (<code class="language-plaintext highlighter-rouge">prod/mysql/terragrunt.hcl</code>) config,
finding the <code class="language-plaintext highlighter-rouge">env.hcl</code> file in the <code class="language-plaintext highlighter-rouge">prod</code> directory.</p>
<h2 id="path_relative_to_include">path_relative_to_include</h2>
<p><code class="language-plaintext highlighter-rouge">path_relative_to_include()</code> returns the relative path between the current <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file and the <code class="language-plaintext highlighter-rouge">path</code> specified in its <code class="language-plaintext highlighter-rouge">include</code> block. For example, consider the following folder structure:</p>
<pre><code class="language-tree">├── terragrunt.hcl
├── prod
|   └── mysql
|       └── terragrunt.hcl
└── stage
    └── mysql
        └── terragrunt.hcl
</code></pre>
<p>Imagine <code class="language-plaintext highlighter-rouge">prod/mysql/terragrunt.hcl</code> and <code class="language-plaintext highlighter-rouge">stage/mysql/terragrunt.hcl</code> include all settings from the root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> can use the <code class="language-plaintext highlighter-rouge">path_relative_to_include()</code> in its <code class="language-plaintext highlighter-rouge">remote_state</code> configuration to ensure each child stores its remote state at a different <code class="language-plaintext highlighter-rouge">key</code>:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">remote_state</span> <span class="p">{</span>
  <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>
  <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>
    <span class="nx">bucket</span> <span class="p">=</span> <span class="s2">"my-terraform-bucket"</span>
    <span class="nx">region</span> <span class="p">=</span> <span class="s2">"us-east-1"</span>
    <span class="nx">key</span>    <span class="p">=</span> <span class="s2">"${path_relative_to_include()}/terraform.tfstate"</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The resulting <code class="language-plaintext highlighter-rouge">key</code> will be <code class="language-plaintext highlighter-rouge">prod/mysql/terraform.tfstate</code> for the prod <code class="language-plaintext highlighter-rouge">mysql</code> module and <code class="language-plaintext highlighter-rouge">stage/mysql/terraform.tfstate</code> for the stage <code class="language-plaintext highlighter-rouge">mysql</code> module.</p>
<p>If you have <code class="language-plaintext highlighter-rouge">include</code> blocks, this function requires a <code class="language-plaintext highlighter-rouge">name</code> parameter when used in the child config to specify which
<code class="language-plaintext highlighter-rouge">include</code> block to base the relative path on.</p>
<p>Example:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
<span class="p">}</span>
<span class="nx">include</span> <span class="s2">"region"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"region.hcl"</span><span class="err">)</span>
<span class="p">}</span>

<span class="nx">terraform</span> <span class="p">{</span>
  <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${path_relative_to_include("</span><span class="nx">root</span><span class="s2">")}"</span>
<span class="p">}</span>
</code></pre></div></div>
<h2 id="path_relative_from_include">path_relative_from_include</h2>
<p><code class="language-plaintext highlighter-rouge">path_relative_from_include()</code> returns the relative path between the <code class="language-plaintext highlighter-rouge">path</code> specified in its <code class="language-plaintext highlighter-rouge">include</code> block and the current <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file (it is the counterpart of <code class="language-plaintext highlighter-rouge">path_relative_to_include()</code>). For example, consider the following folder structure:</p>
<pre><code class="language-tree">├── sources
|  ├── mysql
|  |  └── \*.tf
|  └── secrets
|     └── mysql
|         └── \*.tf
└── terragrunt
  └── common.tfvars
  ├── mysql
  |  └── terragrunt.hcl
  ├── secrets
  |  └── mysql
  |     └── terragrunt.hcl
  └── terragrunt.hcl
</code></pre>
<p>Imagine <code class="language-plaintext highlighter-rouge">terragrunt/mysql/terragrunt.hcl</code> and <code class="language-plaintext highlighter-rouge">terragrunt/secrets/mysql/terragrunt.hcl</code> include all settings from the root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> can use the <code class="language-plaintext highlighter-rouge">path_relative_from_include()</code> in combination with <code class="language-plaintext highlighter-rouge">path_relative_to_include()</code> in its <code class="language-plaintext highlighter-rouge">source</code> configuration to retrieve the relative terraform source code from the terragrunt configuration file:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">terraform</span> <span class="p">{</span>
  <span class="nx">source</span> <span class="p">=</span> <span class="s2">"${path_relative_from_include()}/../sources//${path_relative_to_include()}"</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The resulting <code class="language-plaintext highlighter-rouge">source</code> will be <code class="language-plaintext highlighter-rouge">../../sources//mysql</code> for <code class="language-plaintext highlighter-rouge">mysql</code> module and <code class="language-plaintext highlighter-rouge">../../../sources//secrets/mysql</code> for <code class="language-plaintext highlighter-rouge">secrets/mysql</code> module.</p>
<p>Another use case would be to add extra argument to include the <code class="language-plaintext highlighter-rouge">common.tfvars</code> file for all subdirectories:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code>  <span class="nx">terraform</span> <span class="p">{</span>
    <span class="nx">extra_arguments</span> <span class="s2">"common_var"</span> <span class="p">{</span>
      <span class="nx">commands</span> <span class="p">=</span> <span class="p">[</span>
        <span class="s2">"apply"</span><span class="p">,</span>
        <span class="s2">"plan"</span><span class="p">,</span>
        <span class="s2">"import"</span><span class="p">,</span>
        <span class="s2">"push"</span><span class="p">,</span>
        <span class="s2">"refresh"</span>
      <span class="p">]</span>

      <span class="nx">arguments</span> <span class="p">=</span> <span class="p">[</span>
        <span class="s2">"-var-file=${get_terragrunt_dir()}/${path_relative_from_include()}/common.tfvars"</span><span class="p">,</span>
      <span class="p">]</span>
    <span class="p">}</span>
  <span class="p">}</span>
</code></pre></div></div>
<p>This allows proper retrieval of the <code class="language-plaintext highlighter-rouge">common.tfvars</code> from whatever the level of subdirectories we have.</p>
<p>If you have <code class="language-plaintext highlighter-rouge">include</code> blocks, this function requires a <code class="language-plaintext highlighter-rouge">name</code> parameter when used in the child config to specify which
<code class="language-plaintext highlighter-rouge">include</code> block to base the relative path on.</p>
<p>Example:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
<span class="p">}</span>
<span class="nx">include</span> <span class="s2">"region"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"region.hcl"</span><span class="err">)</span>
<span class="p">}</span>

<span class="nx">terraform</span> <span class="p">{</span>
  <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${path_relative_from_include("</span><span class="nx">root</span><span class="s2">")}"</span>
<span class="p">}</span>
</code></pre></div></div>
<h2 id="get_env">get_env</h2>
<p><code class="language-plaintext highlighter-rouge">get_env(NAME)</code> return the value of variable named <code class="language-plaintext highlighter-rouge">NAME</code> or throws exceptions if that variable is not set. Example:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">remote_state</span> <span class="p">{</span>
  <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>
  <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>
    <span class="nx">bucket</span> <span class="p">=</span> <span class="nx">get_env</span><span class="err">(</span><span class="s2">"BUCKET"</span><span class="err">)</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre></div></div>

### Fix href and src attributes

In [88]:
hrefs = article.find_all(lambda e: e.has_attr("href"))
for href in hrefs:
    if href["href"].startswith("/"):
        href["href"] = BASE + href["href"]
    elif href["href"].startswith("#"):
        href["href"] = url + "/" + href["href"]
srcs = article.find_all(lambda e: e.has_attr("src"))
for src in srcs:
    if src["src"].startswith("/"):
        src["src"] = BASE + src["src"]
article

<div class="cb-doc-content js-scroll-spy" data-scroll-spy-nav-selector="#toc">
<p>Terragrunt allows you to use built-in functions anywhere in <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code>, just like Terraform! The functions currently available are:</p>
<ul>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#terraform-built-in-functions">Terraform built-in functions</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#find_in_parent_folders">find_in_parent_folders</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#path_relative_to_include">path_relative_to_include</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#path_relative_from_include">path_relative_from_include</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_env">get_env</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_platform">get_platform</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_repo_root">get_repo_root</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_path_from_repo_root">get_path_from_repo_root</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_path_to_repo_root">get_path_to_repo_root</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_terragrunt_dir">get_terragrunt_dir</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_working_dir">get_working_dir</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_parent_terragrunt_dir">get_parent_terragrunt_dir</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_original_terragrunt_dir">get_original_terragrunt_dir</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_terraform_commands_that_need_vars">get_terraform_commands_that_need_vars</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_terraform_commands_that_need_input">get_terraform_commands_that_need_input</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_terraform_commands_that_need_locking">get_terraform_commands_that_need_locking</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_terraform_commands_that_need_parallelism">get_terraform_commands_that_need_parallelism</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_aws_account_id">get_aws_account_id</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_aws_caller_identity_arn">get_aws_caller_identity_arn</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_terraform_command">get_terraform_command</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_terraform_cli_args">get_terraform_cli_args</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_default_retryable_errors">get_default_retryable_errors</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_aws_caller_identity_user_id">get_aws_caller_identity_user_id</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd">run_cmd</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#read_terragrunt_config">read_terragrunt_config</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#sops_decrypt_file">sops_decrypt_file</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_terragrunt_source_cli_flag">get_terragrunt_source_cli_flag</a></li>
<li><a href="https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#read_tfvars_file">read_tfvars_file</a></li>
</ul>
<h2 id="terraform-built-in-functions">Terraform built-in functions</h2>
<p>All <a href="https://www.terraform.io/docs/configuration/functions.html">Terraform built-in functions</a> are supported in Terragrunt config files:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">terraform</span> <span class="p">{</span>
  <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${basename(get_terragrunt_dir())}"</span>
<span class="p">}</span>

<span class="nx">remote_state</span> <span class="p">{</span>
  <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>
  <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>
    <span class="nx">bucket</span> <span class="p">=</span> <span class="nx">trimspace</span><span class="err">(</span><span class="s2">"   my-terraform-bucket     "</span><span class="err">)</span>
    <span class="nx">region</span> <span class="p">=</span> <span class="nx">join</span><span class="err">(</span><span class="s2">"-"</span><span class="err">,</span> <span class="p">[</span><span class="s2">"us"</span><span class="p">,</span> <span class="s2">"east"</span><span class="p">,</span> <span class="s2">"1"</span><span class="p">]</span><span class="err">)</span>
    <span class="nx">key</span>    <span class="p">=</span> <span class="nx">format</span><span class="err">(</span><span class="s2">"%s/terraform.tfstate"</span><span class="err">,</span> <span class="nx">path_relative_to_include</span><span class="err">())</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre></div></div>
<p>Note: Any <code class="language-plaintext highlighter-rouge">file*</code> functions (<code class="language-plaintext highlighter-rouge">file</code>, <code class="language-plaintext highlighter-rouge">fileexists</code>, <code class="language-plaintext highlighter-rouge">filebase64</code>, etc) are relative to the directory containing the <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file they’re used in.</p>
<p>Given the following structure:</p>
<pre><code class="language-tree">└── terragrunt
  └── common.tfvars
  ├── assets
  |  └── mysql
  |     └── assets.txt
  └── terragrunt.hcl
</code></pre>
<p>Then <code class="language-plaintext highlighter-rouge">assets.txt</code> could be read with the following function call:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">file</span><span class="err">(</span><span class="s2">"assets/mysql/assets.txt"</span><span class="err">)</span>
</code></pre></div></div>
<h2 id="find_in_parent_folders">find_in_parent_folders</h2>
<p><code class="language-plaintext highlighter-rouge">find_in_parent_folders()</code> searches up the directory tree from the current <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file and returns the absolute path to the first <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> in a parent folder or exit with an error if no such file is found. This is primarily useful in an <code class="language-plaintext highlighter-rouge">include</code> block to automatically find the path to a parent <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The function takes an optional <code class="language-plaintext highlighter-rouge">name</code> parameter that allows you to specify a different path to search for:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-other-file-name.hcl"</span><span class="err">)</span>
<span class="p">}</span>
</code></pre></div></div>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-folder"</span><span class="err">)</span>
<span class="p">}</span>
</code></pre></div></div>
<p>You can also pass an optional second <code class="language-plaintext highlighter-rouge">fallback</code> parameter which causes the function to return the fallback value (instead of exiting with an error) if the file in the <code class="language-plaintext highlighter-rouge">name</code> parameter cannot be found:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-other-file-name.hcl"</span><span class="err">,</span> <span class="s2">"fallback.hcl"</span><span class="err">)</span>
<span class="p">}</span>
</code></pre></div></div>
<p>Note that this function searches relative to the child <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file when called from a parent config. For
example, if you had the following folder structure:</p>
<pre><code class="language-tree">    ├── terragrunt.hcl
    └── prod
        ├── env.hcl
        └── mysql
            └── terragrunt.hcl
</code></pre>
<p>And the root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> contained the following:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">locals</span> <span class="p">{</span>
  <span class="nx">env_vars</span> <span class="p">=</span> <span class="nx">read_terragrunt_config</span><span class="err">(</span><span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"env.hcl"</span><span class="err">))</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The <code class="language-plaintext highlighter-rouge">find_in_parent_folders</code> will search from the <strong>child <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code></strong> (<code class="language-plaintext highlighter-rouge">prod/mysql/terragrunt.hcl</code>) config,
finding the <code class="language-plaintext highlighter-rouge">env.hcl</code> file in the <code class="language-plaintext highlighter-rouge">prod</code> directory.</p>
<h2 id="path_relative_to_include">path_relative_to_include</h2>
<p><code class="language-plaintext highlighter-rouge">path_relative_to_include()</code> returns the relative path between the current <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file and the <code class="language-plaintext highlighter-rouge">path</code> specified in its <code class="language-plaintext highlighter-rouge">include</code> block. For example, consider the following folder structure:</p>
<pre><code class="language-tree">├── terragrunt.hcl
├── prod
|   └── mysql
|       └── terragrunt.hcl
└── stage
    └── mysql
        └── terragrunt.hcl
</code></pre>
<p>Imagine <code class="language-plaintext highlighter-rouge">prod/mysql/terragrunt.hcl</code> and <code class="language-plaintext highlighter-rouge">stage/mysql/terragrunt.hcl</code> include all settings from the root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> can use the <code class="language-plaintext highlighter-rouge">path_relative_to_include()</code> in its <code class="language-plaintext highlighter-rouge">remote_state</code> configuration to ensure each child stores its remote state at a different <code class="language-plaintext highlighter-rouge">key</code>:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">remote_state</span> <span class="p">{</span>
  <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>
  <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>
    <span class="nx">bucket</span> <span class="p">=</span> <span class="s2">"my-terraform-bucket"</span>
    <span class="nx">region</span> <span class="p">=</span> <span class="s2">"us-east-1"</span>
    <span class="nx">key</span>    <span class="p">=</span> <span class="s2">"${path_relative_to_include()}/terraform.tfstate"</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The resulting <code class="language-plaintext highlighter-rouge">key</code> will be <code class="language-plaintext highlighter-rouge">prod/mysql/terraform.tfstate</code> for the prod <code class="language-plaintext highlighter-rouge">mysql</code> module and <code class="language-plaintext highlighter-rouge">stage/mysql/terraform.tfstate</code> for the stage <code class="language-plaintext highlighter-rouge">mysql</code> module.</p>
<p>If you have <code class="language-plaintext highlighter-rouge">include</code> blocks, this function requires a <code class="language-plaintext highlighter-rouge">name</code> parameter when used in the child config to specify which
<code class="language-plaintext highlighter-rouge">include</code> block to base the relative path on.</p>
<p>Example:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
<span class="p">}</span>
<span class="nx">include</span> <span class="s2">"region"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"region.hcl"</span><span class="err">)</span>
<span class="p">}</span>

<span class="nx">terraform</span> <span class="p">{</span>
  <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${path_relative_to_include("</span><span class="nx">root</span><span class="s2">")}"</span>
<span class="p">}</span>
</code></pre></div></div>
<h2 id="path_relative_from_include">path_relative_from_include</h2>
<p><code class="language-plaintext highlighter-rouge">path_relative_from_include()</code> returns the relative path between the <code class="language-plaintext highlighter-rouge">path</code> specified in its <code class="language-plaintext highlighter-rouge">include</code> block and the current <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file (it is the counterpart of <code class="language-plaintext highlighter-rouge">path_relative_to_include()</code>). For example, consider the following folder structure:</p>
<pre><code class="language-tree">├── sources
|  ├── mysql
|  |  └── \*.tf
|  └── secrets
|     └── mysql
|         └── \*.tf
└── terragrunt
  └── common.tfvars
  ├── mysql
  |  └── terragrunt.hcl
  ├── secrets
  |  └── mysql
  |     └── terragrunt.hcl
  └── terragrunt.hcl
</code></pre>
<p>Imagine <code class="language-plaintext highlighter-rouge">terragrunt/mysql/terragrunt.hcl</code> and <code class="language-plaintext highlighter-rouge">terragrunt/secrets/mysql/terragrunt.hcl</code> include all settings from the root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> can use the <code class="language-plaintext highlighter-rouge">path_relative_from_include()</code> in combination with <code class="language-plaintext highlighter-rouge">path_relative_to_include()</code> in its <code class="language-plaintext highlighter-rouge">source</code> configuration to retrieve the relative terraform source code from the terragrunt configuration file:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">terraform</span> <span class="p">{</span>
  <span class="nx">source</span> <span class="p">=</span> <span class="s2">"${path_relative_from_include()}/../sources//${path_relative_to_include()}"</span>
<span class="p">}</span>
</code></pre></div></div>
<p>The resulting <code class="language-plaintext highlighter-rouge">source</code> will be <code class="language-plaintext highlighter-rouge">../../sources//mysql</code> for <code class="language-plaintext highlighter-rouge">mysql</code> module and <code class="language-plaintext highlighter-rouge">../../../sources//secrets/mysql</code> for <code class="language-plaintext highlighter-rouge">secrets/mysql</code> module.</p>
<p>Another use case would be to add extra argument to include the <code class="language-plaintext highlighter-rouge">common.tfvars</code> file for all subdirectories:</p>
<div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code>  <span class="nx">terraform</span> <span class="p">{</span>
    <span class="nx">extra_arguments</span> <span class="s2">"common_var"</span> <span class="p">{</span>
      <span class="nx">commands</span> <span class="p">=</span> <span class="p">[</span>
        <span class="s2">"apply"</span><span class="p">,</span>
        <span class="s2">"plan"</span><span class="p">,</span>
        <span class="s2">"import"</span><span class="p">,</span>
        <span class="s2">"push"</span><span class="p">,</span>
        <span class="s2">"refresh"</span>
      <span class="p">]</span>

      <span class="nx">arguments</span> <span class="p">=</span> <span class="p">[</span>
        <span class="s2">"-var-file=${get_terragrunt_dir()}/${path_relative_from_include()}/common.tfvars"</span><span class="p">,</span>
      <span class="p">]</span>
    <span class="p">}</span>
  <span class="p">}</span>
</code></pre></div></div>
<p>This allows proper retrieval of the <code class="language-plaintext highlighter-rouge">common.tfvars</code> from whatever the level of subdirectories we have.</p>
<p>If you have <code class="language-plaintext highlighter-rouge">include</code> blocks, this function requires a <code class="language-plaintext highlighter-rouge">name</code> parameter when used in the child config to specify which
<code class="language-plaintext highlighter-rouge">include</code> block to base the relative path on.</p>
<p>Example:</p>

### Divide to sections

In [124]:
h2_curr = None
sections = []
children = BeautifulSoup("", "html.parser")
for elem in deepcopy(article).find_all(recursive=False):
    if elem.name == "h2":
        if h2_curr is not None:
            sections.append({"h2": h2_curr, "children": children})
        h2_curr = elem
        children = BeautifulSoup("", "html.parser")
        continue
    children.append(elem)

sections

[{'h2': <h2 id="terraform-built-in-functions">Terraform built-in functions</h2>,
  'children': <p>All <a href="https://www.terraform.io/docs/configuration/functions.html">Terraform built-in functions</a> are supported in Terragrunt config files:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">terraform</span> <span class="p">{</span>
    <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${basename(get_terragrunt_dir())}"</span>
  <span class="p">}</span>

  <span class="nx">remote_state</span> <span class="p">{</span>
    <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>
    <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>
      <span class="nx">bucket</span> <span class="p">=</span> <span class="nx">trimspace</span><span class="err">(</span><span class="s2">"   my-terraform-bucket     "</span><span class="err">)</span>
      <span class="nx">region</span> <span class="p">=</span> <span class="nx">join</span><span class="err">(</span><span class="s2">"-"</span><span class="err">,</span> <span class="p">[</span><span class="s2">"us"</span><span class="p">,</span> <span class="s2">"east"</span><span class="p">,</span> <span class="s2">"1"</span><span class="p">]</span><span class="err">)</span>
      <span class="nx">key</span>    <span class="p">=</span> <span class="nx">format</span><span class="err">(</span><span class="s2">"%s/terraform.tfstate"</span><span class="err">,</span> <span class="nx">path_relative_to_include</span><span class="err">())</span>
    <span class="p">}</span>
  <span class="p">}</span>
  </code></pre></div></div><p>Note: Any <code class="language-plaintext highlighter-rouge">file*</code> functions (<code class="language-plaintext highlighter-rouge">file</code>, <code class="language-plaintext highlighter-rouge">fileexists</code>, <code class="language-plaintext highlighter-rouge">filebase64</code>, etc) are relative to the directory containing the <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file they’re used in.</p><p>Given the following structure:</p><pre><code class="language-tree">└── terragrunt
    └── common.tfvars
    ├── assets
    |  └── mysql
    |     └── assets.txt
    └── terragrunt.hcl
  </code></pre><p>Then <code class="language-plaintext highlighter-rouge">assets.txt</code> could be read with the following function call:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">file</span><span class="err">(</span><span class="s2">"assets/mysql/assets.txt"</span><span class="err">)</span>
  </code></pre></div></div>},
 {'h2': <h2 id="find_in_parent_folders">find_in_parent_folders</h2>,
  'children': <p><code class="language-plaintext highlighter-rouge">find_in_parent_folders()</code> searches up the directory tree from the current <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file and returns the absolute path to the first <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> in a parent folder or exit with an error if no such file is found. This is primarily useful in an <code class="language-plaintext highlighter-rouge">include</code> block to automatically find the path to a parent <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
  <span class="p">}</span>
  </code></pre></div></div><p>The function takes an optional <code class="language-plaintext highlighter-rouge">name</code> parameter that allows you to specify a different path to search for:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-other-file-name.hcl"</span><span class="err">)</span>
  <span class="p">}</span>
  </code></pre></div></div><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-folder"</span><span class="err">)</span>
  <span class="p">}</span>
  </code></pre></div></div><p>You can also pass an optional second <code class="language-plaintext highlighter-rouge">fallback</code> parameter which causes the function to return the fallback value (instead of exiting with an error) if the file in the <code class="language-plaintext highlighter-rouge">name</code> parameter cannot be found:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-other-file-name.hcl"</span><span class="err">,</span> <span class="s2">"fallback.hcl"</span><span class="err">)</span>
  <span class="p">}</span>
  </code></pre></div></div><p>Note that this function searches relative to the child <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file when called from a parent config. For
  example, if you had the following folder structure:</p><pre><code class="language-tree">    ├── terragrunt.hcl
      └── prod
          ├── env.hcl
          └── mysql
              └── terragrunt.hcl
  </code></pre><p>And the root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> contained the following:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">locals</span> <span class="p">{</span>
    <span class="nx">env_vars</span> <span class="p">=</span> <span class="nx">read_terragrunt_config</span><span class="err">(</span><span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"env.hcl"</span><span class="err">))</span>
  <span class="p">}</span>
  </code></pre></div></div><p>The <code class="language-plaintext highlighter-rouge">find_in_parent_folders</code> will search from the <strong>child <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code></strong> (<code class="language-plaintext highlighter-rouge">prod/mysql/terragrunt.hcl</code>) config,
  finding the <code class="language-plaintext highlighter-rouge">env.hcl</code> file in the <code class="language-plaintext highlighter-rouge">prod</code> directory.</p>},
 {'h2': <h2 id="path_relative_to_include">path_relative_to_include</h2>,
  'children': <p><code class="language-plaintext highlighter-rouge">path_relative_to_include()</code> returns the relative path between the current <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file and the <code class="language-plaintext highlighter-rouge">path</code> specified in its <code class="language-plaintext highlighter-rouge">include</code> block. For example, consider the following folder structure:</p><pre><code class="language-tree">├── terragrunt.hcl
  ├── prod
  |   └── mysql
  |       └── terragrunt.hcl
  └── stage
      └── mysql
          └── terragrunt.hcl
  </code></pre><p>Imagine <code class="language-plaintext highlighter-rouge">prod/mysql/terragrunt.hcl</code> and <code class="language-plaintext highlighter-rouge">stage/mysql/terragrunt.hcl</code> include all settings from the root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
  <span class="p">}</span>
  </code></pre></div></div><p>The root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> can use the <code class="language-plaintext highlighter-rouge">path_relative_to_include()</code> in its <code class="language-plaintext highlighter-rouge">remote_state</code> configuration to ensure each child stores its remote state at a different <code class="language-plaintext highlighter-rouge">key</code>:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">remote_state</span> <span class="p">{</span>
    <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>
    <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>
      <span class="nx">bucket</span> <span class="p">=</span> <span class="s2">"my-terraform-bucket"</span>
      <span class="nx">region</span> <span class="p">=</span> <span class="s2">"us-east-1"</span>
      <span class="nx">key</span>    <span class="p">=</span> <span class="s2">"${path_relative_to_include()}/terraform.tfstate"</span>
    <span class="p">}</span>
  <span class="p">}</span>
  </code></pre></div></div><p>The resulting <code class="language-plaintext highlighter-rouge">key</code> will be <code class="language-plaintext highlighter-rouge">prod/mysql/terraform.tfstate</code> for the prod <code class="language-plaintext highlighter-rouge">mysql</code> module and <code class="language-plaintext highlighter-rouge">stage/mysql/terraform.tfstate</code> for the stage <code class="language-plaintext highlighter-rouge">mysql</code> module.</p><p>If you have <code class="language-plaintext highlighter-rouge">include</code> blocks, this function requires a <code class="language-plaintext highlighter-rouge">name</code> parameter when used in the child config to specify which
  <code class="language-plaintext highlighter-rouge">include</code> block to base the relative path on.</p><p>Example:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
  <span class="p">}</span>
  <span class="nx">include</span> <span class="s2">"region"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"region.hcl"</span><span class="err">)</span>
  <span class="p">}</span>

  <span class="nx">terraform</span> <span class="p">{</span>
    <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${path_relative_to_include("</span><span class="nx">root</span><span class="s2">")}"</span>
  <span class="p">}</span>
  </code></pre></div></div>},
 {'h2': <h2 id="path_relative_from_include">path_relative_from_include</h2>,
  'children': <p><code class="language-plaintext highlighter-rouge">path_relative_from_include()</code> returns the relative path between the <code class="language-plaintext highlighter-rouge">path</code> specified in its <code class="language-plaintext highlighter-rouge">include</code> block and the current <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file (it is the counterpart of <code class="language-plaintext highlighter-rouge">path_relative_to_include()</code>). For example, consider the following folder structure:</p><pre><code class="language-tree">├── sources
  |  ├── mysql
  |  |  └── \*.tf
  |  └── secrets
  |     └── mysql
  |         └── \*.tf
  └── terragrunt
    └── common.tfvars
    ├── mysql
    |  └── terragrunt.hcl
    ├── secrets
    |  └── mysql
    |     └── terragrunt.hcl
    └── terragrunt.hcl
  </code></pre><p>Imagine <code class="language-plaintext highlighter-rouge">terragrunt/mysql/terragrunt.hcl</code> and <code class="language-plaintext highlighter-rouge">terragrunt/secrets/mysql/terragrunt.hcl</code> include all settings from the root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
  <span class="p">}</span>
  </code></pre></div></div><p>The root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> can use the <code class="language-plaintext highlighter-rouge">path_relative_from_include()</code> in combination with <code class="language-plaintext highlighter-rouge">path_relative_to_include()</code> in its <code class="language-plaintext highlighter-rouge">source</code> configuration to retrieve the relative terraform source code from the terragrunt configuration file:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">terraform</span> <span class="p">{</span>
    <span class="nx">source</span> <span class="p">=</span> <span class="s2">"${path_relative_from_include()}/../sources//${path_relative_to_include()}"</span>
  <span class="p">}</span>
  </code></pre></div></div><p>The resulting <code class="language-plaintext highlighter-rouge">source</code> will be <code class="language-plaintext highlighter-rouge">../../sources//mysql</code> for <code class="language-plaintext highlighter-rouge">mysql</code> module and <code class="language-plaintext highlighter-rouge">../../../sources//secrets/mysql</code> for <code class="language-plaintext highlighter-rouge">secrets/mysql</code> module.</p><p>Another use case would be to add extra argument to include the <code class="language-plaintext highlighter-rouge">common.tfvars</code> file for all subdirectories:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code>  <span class="nx">terraform</span> <span class="p">{</span>
      <span class="nx">extra_arguments</span> <span class="s2">"common_var"</span> <span class="p">{</span>
        <span class="nx">commands</span> <span class="p">=</span> <span class="p">[</span>
          <span class="s2">"apply"</span><span class="p">,</span>
          <span class="s2">"plan"</span><span class="p">,</span>
          <span class="s2">"import"</span><span class="p">,</span>
          <span class="s2">"push"</span><span class="p">,</span>
          <span class="s2">"refresh"</span>
        <span class="p">]</span>

        <span class="nx">arguments</span> <span class="p">=</span> <span class="p">[</span>
          <span class="s2">"-var-file=${get_terragrunt_dir()}/${path_relative_from_include()}/common.tfvars"</span><span class="p">,</span>
        <span class="p">]</span>
      <span class="p">}</span>
    <span class="p">}</span>
  </code></pre></div></div><p>This allows proper retrieval of the <code class="language-plaintext highlighter-rouge">common.tfvars</code> from whatever the level of subdirectories we have.</p><p>If you have <code class="language-plaintext highlighter-rouge">include</code> blocks, this function requires a <code class="language-plaintext highlighter-rouge">name</code> parameter when used in the child config to specify which
  <code class="language-plaintext highlighter-rouge">include</code> block to base the relative path on.</p><p>Example:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
  <span class="p">}</span>
  <span class="nx">include</span> <span class="s2">"region"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"region.hcl"</span><span class="err">)</span>
  <span class="p">}</span>

  <span class="nx">terraform</span> <span class="p">{</span>
    <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${path_relative_from_include("</span><span class="nx">root</span><span class="s2">")}"</span>
  <span class="p">}</span>
  </code></pre></div></div>},
 {'h2': <h2 id="get_env">get_env</h2>,
  'children': <p><code class="language-plaintext highlighter-rouge">get_env(NAME)</code> return the value of variable named <code class="language-plaintext highlighter-rouge">NAME</code> or throws exceptions if that variable is not set. Example:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">remote_state</span> <span class="p">{</span>
    <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>
    <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>
      <span class="nx">bucket</span> <span class="p">=</span> <span class="nx">get_env</span><span class="err">(</span><span class="s2">"BUCKET"</span><span class="err">)</span>
    <span class="p">}</span>
  <span class="p">}</span>
  </code></pre></div></div><p><code class="language-plaintext highlighter-rouge">get_env(NAME, DEFAULT)</code> returns the value of the environment variable named <code class="language-plaintext highlighter-rouge">NAME</code> or <code class="language-plaintext highlighter-rouge">DEFAULT</code> if that environment variable is not set. Example:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">remote_state</span> <span class="p">{</span>
    <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>
    <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>
      <span class="nx">bucket</span> <span class="p">=</span> <span class="nx">get_env</span><span class="err">(</span><span class="s2">"BUCKET"</span><span class="err">,</span> <span class="s2">"my-terraform-bucket"</span><span class="err">)</span>
    <span class="p">}</span>
  <span class="p">}</span>
  </code></pre></div></div><p>Note that <a href="https://www.terraform.io/docs/configuration/environment-variables.html#tf_var_name">Terraform will read environment variables</a> that start with the prefix <code class="language-plaintext highlighter-rouge">TF_VAR_</code>, so one way to share a variable named <code class="language-plaintext highlighter-rouge">foo</code> between Terraform and Terragrunt is to set its value as the environment variable <code class="language-plaintext highlighter-rouge">TF_VAR_foo</code> and to read that value in using this <code class="language-plaintext highlighter-rouge">get_env()</code> built-in function.</p>},
 {'h2': <h2 id="get_platform">get_platform</h2>,
  'children': <p><code class="language-plaintext highlighter-rouge">get_platform()</code> returns the current Operating System. Example:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">inputs</span> <span class="err">=</span> <span class="p">{</span>

In [136]:
enriched = []
for section in sections:
    title = section["h2"].string
    summary = section["children"].find("p").text
    summary = re.split(r"\.\s", summary)[0] + "."
    summary = summary.replace(title, "___")
    # details_with_header = BeautifulSoup(title.prettify() + section["children"].prettify(), "html.parser")
    details = section["children"].prettify()
    details_with_header = BeautifulSoup(
        section["h2"].prettify() + details,
        "html.parser",
    ).prettify()

    enriched.append(
        {
            **section,
            "title": title,
            "summary": summary,
            "details": details,
            "details_with_header": details_with_header,
            # "tags": [],
        }
    )

enriched

[{'h2': <h2 id="terraform-built-in-functions">Terraform built-in functions</h2>,
  'children': <p>All <a href="https://www.terraform.io/docs/configuration/functions.html">Terraform built-in functions</a> are supported in Terragrunt config files:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">terraform</span> <span class="p">{</span>
    <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${basename(get_terragrunt_dir())}"</span>
  <span class="p">}</span>

  <span class="nx">remote_state</span> <span class="p">{</span>
    <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>
    <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>
      <span class="nx">bucket</span> <span class="p">=</span> <span class="nx">trimspace</span><span class="err">(</span><span class="s2">"   my-terraform-bucket     "</span><span class="err">)</span>
      <span class="nx">region</span> <span class="p">=</span> <span class="nx">join</span><span class="err">(</span><span class="s2">"-"</span><span class="err">,</span> <span class="p">[</span><span class="s2">"us"</span><span class="p">,</span> <span class="s2">"east"</span><span class="p">,</span> <span class="s2">"1"</span><span class="p">]</span><span class="err">)</span>
      <span class="nx">key</span>    <span class="p">=</span> <span class="nx">format</span><span class="err">(</span><span class="s2">"%s/terraform.tfstate"</span><span class="err">,</span> <span class="nx">path_relative_to_include</span><span class="err">())</span>
    <span class="p">}</span>
  <span class="p">}</span>
  </code></pre></div></div><p>Note: Any <code class="language-plaintext highlighter-rouge">file*</code> functions (<code class="language-plaintext highlighter-rouge">file</code>, <code class="language-plaintext highlighter-rouge">fileexists</code>, <code class="language-plaintext highlighter-rouge">filebase64</code>, etc) are relative to the directory containing the <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file they’re used in.</p><p>Given the following structure:</p><pre><code class="language-tree">└── terragrunt
    └── common.tfvars
    ├── assets
    |  └── mysql
    |     └── assets.txt
    └── terragrunt.hcl
  </code></pre><p>Then <code class="language-plaintext highlighter-rouge">assets.txt</code> could be read with the following function call:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">file</span><span class="err">(</span><span class="s2">"assets/mysql/assets.txt"</span><span class="err">)</span>
  </code></pre></div></div>,
  'title': 'Terraform built-in functions',
  'summary': 'All ___ are supported in Terragrunt config files:.',
  'details': '<p>\n All\n <a href="https://www.terraform.io/docs/configuration/functions.html">\n  Terraform built-in functions\n </a>\n are supported in Terragrunt config files:\n</p>\n<div class="language-hcl highlighter-rouge">\n <div class="highlight">\n  <pre class="highlight"><code><span class="nx">terraform</span> <span class="p">{</span>\n  <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${basename(get_terragrunt_dir())}"</span>\n<span class="p">}</span>\n\n<span class="nx">remote_state</span> <span class="p">{</span>\n  <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>\n  <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>\n    <span class="nx">bucket</span> <span class="p">=</span> <span class="nx">trimspace</span><span class="err">(</span><span class="s2">"   my-terraform-bucket     "</span><span class="err">)</span>\n    <span class="nx">region</span> <span class="p">=</span> <span class="nx">join</span><span class="err">(</span><span class="s2">"-"</span><span class="err">,</span> <span class="p">[</span><span class="s2">"us"</span><span class="p">,</span> <span class="s2">"east"</span><span class="p">,</span> <span class="s2">"1"</span><span class="p">]</span><span class="err">)</span>\n    <span class="nx">key</span>    <span class="p">=</span> <span class="nx">format</span><span class="err">(</span><span class="s2">"%s/terraform.tfstate"</span><span class="err">,</span> <span class="nx">path_relative_to_include</span><span class="err">())</span>\n  <span class="p">}</span>\n<span class="p">}</span>\n</code></pre>\n </div>\n</div>\n<p>\n Note: Any\n <code class="language-plaintext highlighter-rouge">\n  file*\n </code>\n functions (\n <code class="language-plaintext highlighter-rouge">\n  file\n </code>\n ,\n <code class="language-plaintext highlighter-rouge">\n  fileexists\n </code>\n ,\n <code class="language-plaintext highlighter-rouge">\n  filebase64\n </code>\n , etc) are relative to the directory containing the\n <code class="language-plaintext highlighter-rouge">\n  terragrunt.hcl\n </code>\n file they’re used in.\n</p>\n<p>\n Given the following structure:\n</p>\n<pre><code class="language-tree">└── terragrunt\n  └── common.tfvars\n  ├── assets\n  |  └── mysql\n  |     └── assets.txt\n  └── terragrunt.hcl\n</code></pre>\n<p>\n Then\n <code class="language-plaintext highlighter-rouge">\n  assets.txt\n </code>\n could be read with the following function call:\n</p>\n<div class="language-hcl highlighter-rouge">\n <div class="highlight">\n  <pre class="highlight"><code><span class="nx">file</span><span class="err">(</span><span class="s2">"assets/mysql/assets.txt"</span><span class="err">)</span>\n</code></pre>\n </div>\n</div>\n',
  'details_with_header': '<h2 id="terraform-built-in-functions">\n Terraform built-in functions\n</h2>\n<p>\n All\n <a href="https://www.terraform.io/docs/configuration/functions.html">\n  Terraform built-in functions\n </a>\n are supported in Terragrunt config files:\n</p>\n<div class="language-hcl highlighter-rouge">\n <div class="highlight">\n  <pre class="highlight"><code><span class="nx">terraform</span> <span class="p">{</span>\n  <span class="nx">source</span> <span class="p">=</span> <span class="s2">"../modules/${basename(get_terragrunt_dir())}"</span>\n<span class="p">}</span>\n\n<span class="nx">remote_state</span> <span class="p">{</span>\n  <span class="nx">backend</span> <span class="p">=</span> <span class="s2">"s3"</span>\n  <span class="nx">config</span> <span class="p">=</span> <span class="p">{</span>\n    <span class="nx">bucket</span> <span class="p">=</span> <span class="nx">trimspace</span><span class="err">(</span><span class="s2">"   my-terraform-bucket     "</span><span class="err">)</span>\n    <span class="nx">region</span> <span class="p">=</span> <span class="nx">join</span><span class="err">(</span><span class="s2">"-"</span><span class="err">,</span> <span class="p">[</span><span class="s2">"us"</span><span class="p">,</span> <span class="s2">"east"</span><span class="p">,</span> <span class="s2">"1"</span><span class="p">]</span><span class="err">)</span>\n    <span class="nx">key</span>    <span class="p">=</span> <span class="nx">format</span><span class="err">(</span><span class="s2">"%s/terraform.tfstate"</span><span class="err">,</span> <span class="nx">path_relative_to_include</span><span class="err">())</span>\n  <span class="p">}</span>\n<span class="p">}</span>\n</code></pre>\n </div>\n</div>\n<p>\n Note: Any\n <code class="language-plaintext highlighter-rouge">\n  file*\n </code>\n functions (\n <code class="language-plaintext highlighter-rouge">\n  file\n </code>\n ,\n <code class="language-plaintext highlighter-rouge">\n  fileexists\n </code>\n ,\n <code class="language-plaintext highlighter-rouge">\n  filebase64\n </code>\n , etc) are relative to the directory containing the\n <code class="language-plaintext highlighter-rouge">\n  terragrunt.hcl\n </code>\n file they’re used in.\n</p>\n<p>\n Given the following structure:\n</p>\n<pre><code class="language-tree">└── terragrunt\n  └── common.tfvars\n  ├── assets\n  |  └── mysql\n  |     └── assets.txt\n  └── terragrunt.hcl\n</code></pre>\n<p>\n Then\n <code class="language-plaintext highlighter-rouge">\n  assets.txt\n </code>\n could be read with the following function call:\n</p>\n<div class="language-hcl highlighter-rouge">\n <div class="highlight">\n  <pre class="highlight"><code><span class="nx">file</span><span class="err">(</span><span class="s2">"assets/mysql/assets.txt"</span><span class="err">)</span>\n</code></pre>\n </div>\n</div>\n'},
 {'h2': <h2 id="find_in_parent_folders">find_in_parent_folders</h2>,
  'children': <p><code class="language-plaintext highlighter-rouge">find_in_parent_folders()</code> searches up the directory tree from the current <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file and returns the absolute path to the first <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> in a parent folder or exit with an error if no such file is found. This is primarily useful in an <code class="language-plaintext highlighter-rouge">include</code> block to automatically find the path to a parent <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>
  <span class="p">}</span>
  </code></pre></div></div><p>The function takes an optional <code class="language-plaintext highlighter-rouge">name</code> parameter that allows you to specify a different path to search for:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-other-file-name.hcl"</span><span class="err">)</span>
  <span class="p">}</span>
  </code></pre></div></div><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-folder"</span><span class="err">)</span>
  <span class="p">}</span>
  </code></pre></div></div><p>You can also pass an optional second <code class="language-plaintext highlighter-rouge">fallback</code> parameter which causes the function to return the fallback value (instead of exiting with an error) if the file in the <code class="language-plaintext highlighter-rouge">name</code> parameter cannot be found:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>
    <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-other-file-name.hcl"</span><span class="err">,</span> <span class="s2">"fallback.hcl"</span><span class="err">)</span>
  <span class="p">}</span>
  </code></pre></div></div><p>Note that this function searches relative to the child <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> file when called from a parent config. For
  example, if you had the following folder structure:</p><pre><code class="language-tree">    ├── terragrunt.hcl
      └── prod
          ├── env.hcl
          └── mysql
              └── terragrunt.hcl
  </code></pre><p>And the root <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code> contained the following:</p><div class="language-hcl highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">locals</span> <span class="p">{</span>
    <span class="nx">env_vars</span> <span class="p">=</span> <span class="nx">read_terragrunt_config</span><span class="err">(</span><span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"env.hcl"</span><span class="err">))</span>
  <span class="p">}</span>
  </code></pre></div></div><p>The <code class="language-plaintext highlighter-rouge">find_in_parent_folders</code> will search from the <strong>child <code class="language-plaintext highlighter-rouge">terragrunt.hcl</code></strong> (<code class="language-plaintext highlighter-rouge">prod/mysql/terragrunt.hcl</code>) config,
  finding the <code class="language-plaintext highlighter-rouge">env.hcl</code> file in the <code class="language-plaintext highlighter-rouge">prod</code> directory.</p>,
  'title': 'find_in_parent_folders',
  'summary': '___() searches up the directory tree from the current terragrunt.hcl file and returns the absolute path to the first terragrunt.hcl in a parent folder or exit with an error if no such file is found.',
  'details': '<p>\n <code class="language-plaintext highlighter-rouge">\n  find_in_parent_folders()\n </code>\n searches up the directory tree from the current\n <code class="language-plaintext highlighter-rouge">\n  terragrunt.hcl\n </code>\n file and returns the absolute path to the first\n <code class="language-plaintext highlighter-rouge">\n  terragrunt.hcl\n </code>\n in a parent folder or exit with an error if no such file is found. This is primarily useful in an\n <code class="language-plaintext highlighter-rouge">\n  include\n </code>\n block to automatically find the path to a parent\n <code class="language-plaintext highlighter-rouge">\n  terragrunt.hcl\n </code>\n file:\n</p>\n<div class="language-hcl highlighter-rouge">\n <div class="highlight">\n  <pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>\n  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">()</span>\n<span class="p">}</span>\n</code></pre>\n </div>\n</div>\n<p>\n The function takes an optional\n <code class="language-plaintext highlighter-rouge">\n  name\n </code>\n parameter that allows you to specify a different path to search for:\n</p>\n<div class="language-hcl highlighter-rouge">\n <div class="highlight">\n  <pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>\n  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-other-file-name.hcl"</span><span class="err">)</span>\n<span class="p">}</span>\n</code></pre>\n </div>\n</div>\n<div class="language-hcl highlighter-rouge">\n <div class="highlight">\n  <pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>\n  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-folder"</span><span class="err">)</span>\n<span class="p">}</span>\n</code></pre>\n </div>\n</div>\n<p>\n You can also pass an optional second\n <code class="language-plaintext highlighter-rouge">\n  fallback\n </code>\n parameter which causes the function to return the fallback value (instead of exiting with an error) if the file in the\n <code class="language-plaintext highlighter-rouge">\n  name\n </code>\n parameter cannot be found:\n</p>\n<div class="language-hcl highlighter-rouge">\n <div class="highlight">\n  <pre class="highlight"><code><span class="nx">include</span> <span class="s2">"root"</span> <span class="p">{</span>\n  <span class="nx">path</span> <span class="p">=</span> <span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"some-other-file-name.hcl"</span><span class="err">,</span> <span class="s2">"fallback.hcl"</span><span class="err">)</span>\n<span class="p">}</span>\n</code></pre>\n </div>\n</div>\n<p>\n Note that this function searches relative to the child\n <code class="language-plaintext highlighter-rouge">\n  terragrunt.hcl\n </code>\n file when called from a parent config. For\nexample, if you had the following folder structure:\n</p>\n<pre><code class="language-tree">    ├── terragrunt.hcl\n    └── prod\n        ├── env.hcl\n        └── mysql\n            └── terragrunt.hcl\n</code></pre>\n<p>\n And the root\n <code class="language-plaintext highlighter-rouge">\n  terragrunt.hcl\n </code>\n contained the following:\n</p>\n<div class="language-hcl highlighter-rouge">\n <div class="highlight">\n  <pre class="highlight"><code><span class="nx">locals</span> <span class="p">{</span>\n  <span class="nx">env_vars</span> <span class="p">=</span> <span class="nx">read_terragrunt_config</span><span class="err">(</span><span class="nx">find_in_parent_folders</span><span class="err">(</span><span class="s2">"env.hcl"</span><span class="err">))</span>\n<span class="p">}</span>\n</code></pre>\n </div>\n</div>\n<p>\n The\n <code class="language-plaintext highlighter-rouge">\n  find_in_parent_folders\n </code>\n will search from the\n <strong>\n  child\n  <code class="language-plaintext highlighter-rouge">\n   terragrunt.hcl\n  </code>\n </strong>\n (\n <code class="language-plaintext highlighter-rouge">\n  prod/mysql/terragrunt.hcl\n </code>\n ) config,\nfinding the\n <code class="language-plaintext highlighter-rouge">\n  env.hcl\n </code>\n file in the\n <code class="language-plaintext highlighter-rouge">\n  prod\n </code>\n directory.\n</p>\n',

In [137]:
functions = pd.DataFrame(enriched)[
    ["title", "summary", "details_with_header", "details"]
]
functions

,title,summary,details_with_header,details
0,Terraform built-in functions,All ___ are supported in Terragrunt config fil...,"<h2 id=""terraform-built-in-functions"">\n Terra...","<p>\n All\n <a href=""https://www.terraform.io/..."
1,find_in_parent_folders,___() searches up the directory tree from the ...,"<h2 id=""find_in_parent_folders"">\n find_in_par...","<p>\n <code class=""language-plaintext highligh..."
2,path_relative_to_include,___() returns the relative path between the cu...,"<h2 id=""path_relative_to_include"">\n path_rela...","<p>\n <code class=""language-plaintext highligh..."
3,path_relative_from_include,___() returns the relative path between the pa...,"<h2 id=""path_relative_from_include"">\n path_re...","<p>\n <code class=""language-plaintext highligh..."
4,get_env,___(NAME) return the value of variable named N...,"<h2 id=""get_env"">\n get_env\n</h2>\n<p>\n <cod...","<p>\n <code class=""language-plaintext highligh..."
5,get_platform,___() returns the current Operating System.,"<h2 id=""get_platform"">\n get_platform\n</h2>\n...","<p>\n <code class=""language-plaintext highligh..."
6,get_repo_root,___() returns the absolute path to the root of...,"<h2 id=""get_repo_root"">\n get_repo_root\n</h2>...","<p>\n <code class=""language-plaintext highligh..."
7,get_path_from_repo_root,___() returns the path from the root of the Gi...,"<h2 id=""get_path_from_repo_root"">\n get_path_f...","<p>\n <code class=""language-plaintext highligh..."
8,get_path_to_repo_root,___() returns the relative path to the root of...,"<h2 id=""get_path_to_repo_root"">\n get_path_to_...","<p>\n <code class=""language-plaintext highligh..."
9,get_terragrunt_dir,___() returns the directory where the Terragru...,"<h2 id=""get_terragrunt_dir"">\n get_terragrunt_...","<p>\n <code class=""language-plaintext highligh..."
10,get_working_dir,___() returns the absolute path where Terragru...,"<h2 id=""get_working_dir"">\n get_working_dir\n<...","<p>\n <code class=""language-plaintext highligh..."
11,get_parent_terragrunt_dir,___() returns the absolute directory where the...,"<h2 id=""get_parent_terragrunt_dir"">\n get_pare...","<p>\n <code class=""language-plaintext highligh..."
12,get_original_terragrunt_dir,___() returns the directory where the original...,"<h2 id=""get_original_terragrunt_dir"">\n get_or...","<p>\n <code class=""language-plaintext highligh..."
13,get_terraform_commands_that_need_vars,___() returns the list of terraform commands t...,"<h2 id=""get_terraform_commands_that_need_vars""...","<p>\n <code class=""language-plaintext highligh..."
14,get_terraform_commands_that_need_input,___() returns the list of terraform commands t...,"<h2 id=""get_terraform_commands_that_need_input...","<p>\n <code class=""language-plaintext highligh..."
15,get_terraform_commands_that_need_locking,___() returns the list of terraform commands t...,"<h2 id=""get_terraform_commands_that_need_locki...","<p>\n <code class=""language-plaintext highligh..."
16,get_terraform_commands_that_need_parallelism,___() returns the list of terraform commands t...,"<h2 id=""get_terraform_commands_that_need_paral...","<p>\n <code class=""language-plaintext highligh..."
17,get_aws_account_id,___() returns the AWS account id associated wi...,"<h2 id=""get_aws_account_id"">\n get_aws_account...","<p>\n <code class=""language-plaintext highligh..."
18,get_aws_caller_identity_arn,___() returns the ARN of the AWS identity asso...,"<h2 id=""get_aws_caller_identity_arn"">\n get_aw...","<p>\n <code class=""language-plaintext highligh..."
19,get_terraform_command,___() returns the current terraform command in...,"<h2 id=""get_terraform_command"">\n get_terrafor...","<p>\n <code class=""language-plaintext highligh..."
20,get_terraform_cli_args,___() returns cli args for the current terrafo...,"<h2 id=""get_terraform_cli_args"">\n get_terrafo...","<p>\n <code class=""language-plaintext highligh..."
21,get_default_retryable_errors,___() returns default retryabled errors.,"<h2 id=""get_default_retryable_errors"">\n get_d...","<p>\n <code class=""language-plaintext highligh..."
22,get_aws_caller_identity_user_id,___() returns the UserId of the AWS identity a...,"<h2 id=""get_aws_caller_identity_user_id"">\n ge...","<p>\n <code class=""language-plaintext highligh..."
23,run_cmd,"___(command, arg1, arg2…​) runs a shell comman...","<h2 id=""run_cmd"">\n run_cmd\n</h2>\n<p>\n <cod...","<p>\n <code class=""language-plaintext highligh..."
24,read_terragrunt_config,"___(config_path, [default_val]) parses the ter...","<h2 id=""read_terragrunt_config"">\n read_terrag...","<p>\n <code class=""language-plaintext highligh..."
25,sops_decrypt_file,"___(file_path) decrypts a yaml, json, ini, env...","<h2 id=""sops_decrypt_file"">\n sops_decrypt_fil...","<p>\n <code class=""language-plaintext highligh..."
26,get_terragrunt_source_cli_flag,___() returns the value passed in via the CLI ...,"<h2 id=""get_terragrunt_source_cli_flag"">\n get...","<p>\n <code class=""language-plaintext highligh..."

In [141]:
forwards = functions[["title", "details"]].copy()
forwards = forwards.rename(columns={"title": "front", "details": "back"})
backwards = functions[["summary", "details_with_header"]].copy()
backwards = backwards.rename(
    columns={"summary": "front", "details_with_header": "back"}
)
combined = pd.concat([forwards, backwards], ignore_index=True)
combined

,front,back
0,Terraform built-in functions,"<p>\n All\n <a href=""https://www.terraform.io/..."
1,find_in_parent_folders,"<p>\n <code class=""language-plaintext highligh..."
2,path_relative_to_include,"<p>\n <code class=""language-plaintext highligh..."
3,path_relative_from_include,"<p>\n <code class=""language-plaintext highligh..."
4,get_env,"<p>\n <code class=""language-plaintext highligh..."
5,get_platform,"<p>\n <code class=""language-plaintext highligh..."
6,get_repo_root,"<p>\n <code class=""language-plaintext highligh..."
7,get_path_from_repo_root,"<p>\n <code class=""language-plaintext highligh..."
8,get_path_to_repo_root,"<p>\n <code class=""language-plaintext highligh..."
9,get_terragrunt_dir,"<p>\n <code class=""language-plaintext highligh..."
10,get_working_dir,"<p>\n <code class=""language-plaintext highligh..."
11,get_parent_terragrunt_dir,"<p>\n <code class=""language-plaintext highligh..."
12,get_original_terragrunt_dir,"<p>\n <code class=""language-plaintext highligh..."
13,get_terraform_commands_that_need_vars,"<p>\n <code class=""language-plaintext highligh..."
14,get_terraform_commands_that_need_input,"<p>\n <code class=""language-plaintext highligh..."
15,get_terraform_commands_that_need_locking,"<p>\n <code class=""language-plaintext highligh..."
16,get_terraform_commands_that_need_parallelism,"<p>\n <code class=""language-plaintext highligh..."
17,get_aws_account_id,"<p>\n <code class=""language-plaintext highligh..."
18,get_aws_caller_identity_arn,"<p>\n <code class=""language-plaintext highligh..."
19,get_terraform_command,"<p>\n <code class=""language-plaintext highligh..."
20,get_terraform_cli_args,"<p>\n <code class=""language-plaintext highligh..."
21,get_default_retryable_errors,"<p>\n <code class=""language-plaintext highligh..."
22,get_aws_caller_identity_user_id,"<p>\n <code class=""language-plaintext highligh..."
23,run_cmd,"<p>\n <code class=""language-plaintext highligh..."
24,read_terragrunt_config,"<p>\n <code class=""language-plaintext highligh..."
25,sops_decrypt_file,"<p>\n <code class=""language-plaintext highligh..."
26,get_terragrunt_source_cli_flag,"<p>\n <code class=""language-plaintext highligh..."
27,All ___ are supported in Terragrunt config fil...,"<h2 id=""terraform-built-in-functions"">\n Terra..."
28,___() searches up the directory tree from the ...,"<h2 id=""find_in_parent_folders"">\n find_in_par..."
29,___() returns the relative path between the cu...,"<h2 id=""path_relative_to_include"">\n path_rela..."
30,___() returns the relative path between the pa...,"<h2 id=""path_relative_from_include"">\n path_re..."
31,___(NAME) return the value of variable named N...,"<h2 id=""get_env"">\n get_env\n</h2>\n<p>\n <cod..."
32,___() returns the current Operating System.,"<h2 id=""get_platform"">\n get_platform\n</h2>\n..."
33,___() returns the absolute path to the root of...,"<h2 id=""get_repo_root"">\n get_repo_root\n</h2>..."
34,___() returns the path from the root of the Gi...,"<h2 id=""get_path_from_repo_root"">\n get_path_f..."
35,___() returns the relative path to the root of...,"<h2 id=""get_path_to_repo_root"">\n get_path_to_..."
36,___() returns the directory where the Terragru...,"<h2 id=""get_terragrunt_dir"">\n get_terragrunt_..."
37,___() returns the absolute path where Terragru...,"<h2 id=""get_working_dir"">\n get_working_dir\n<..."
38,___() returns the absolute directory where the...,"<h2 id=""get_parent_terragrunt_dir"">\n get_pare..."
39,___() returns the directory where the original...,"<h2 id=""get_original_terragrunt_dir"">\n get_or..."
40,___() returns the list of terraform commands t...,"<h2 id=""get_terraform_commands_that_need_vars""..."
41,___() returns the list of terraform commands t...,"<h2 id=""get_terraform_commands_that_need_input..."
42,___() returns the list of terraform commands t...,"<h2 id=""get_terraform_commands_that_need_locki..."
43,___() returns the list of terraform commands t...,"<h2 id=""get_terraform_commands_that_need_paral..."
44,___() returns the AWS account id associated wi...,"<h2 id=""get_aws_account_id"">\n get_aws_account..."
45,___() returns the ARN of the AWS identity asso...,"<h2 id=""get_aws_caller_identity_arn"">\n get_aw..."
46,___() returns the current terraform command in...,"<h2 id=""get_terraform_command"">\n get_terrafor..."
47,___() returns cli args for the current terrafo...,"<h2 id=""get_terraform_cli_args"">\n get_terrafo..."
48,___() returns default retryabled errors.,"<h2 id=""get_default_retryable_errors"">\n get_d..."
49,___() returns the UserId of the AWS identity a...,"<h2 id=""get_aws_caller_identity_user_id"">\n ge..."
50,"___(command, arg1, arg2…​) runs a shell comman...","<h2 id=""run_cmd"">\n run_cmd\n</h2>\n<p>\n <cod..."
51,"___(config_path, [default_val]) parses the ter...","<h2 id=""read_terragrunt_config"">\n read_terrag..."
52,"___(file_path) decrypts a yaml, json, ini, env...","<h2 id=""sops_decrypt_file"">\n sops_decrypt_fil..."
53,___() returns the value passed in via the CLI ...,"<h2 id=""get_terragrunt_source_cli_flag"">\n get..."

In [143]:
combined.to_csv(artifact_csv_abspath, sep=":", index=False, header=False)