In [1]:
import pandas as pd
from os.path import join, abspath
from bs4 import BeautifulSoup
from bs4.element import NavigableString
import numpy as np
from IPython.display import display
import re
from requests import get
from bs4 import BeautifulSoup
from urllib.parse import urlparse
from copy import deepcopy

artifacts_abspath = abspath("../../../artifacts")
assets_abspath = abspath("../../../assets")
source_abspath = join(assets_abspath, "evm/opcodes.xlsx")
target_abspath = join(artifacts_abspath, "evm/opcodes_with_unique_card.csv")
options = [
    "display.max_rows",
    None,
    "display.max_columns",
    None,
    "display.max_colwidth",
    None,
]

In [2]:
notes_remove = "(opens in a new tab)"
source = pd.read_excel(source_abspath, sheet_name="Sheet")
source.rename(
    columns={
        "Stack": "Opcode",
        "Name": "Mnemonic",
        "Initial Stack": "Inputs",
        "Resulting Stack": "Output",
    },
    inplace=True,
)


def notes_rewrite(v):
    if pd.isna(v):
        return v
    v = v.replace(notes_remove, "")
    v = v[0].upper() + v[1:]
    v = v.replace("Uint", "uint")
    return v


source["Notes"] = source["Notes"].apply(notes_rewrite)
with pd.option_context(*options):
    display(source)

,Opcode,Mnemonic,Gas Constant,Gas Dynamic,Inputs,Output,Mem / Storage,Notes
0,00,STOP,0,NaN,NaN,NaN,NaN,Halt execution
1,01,ADD,3,NaN,"a, b",a + b,NaN,(u)int256 addition modulo 2**256
2,02,MUL,5,NaN,"a, b",a * b,NaN,(u)int256 multiplication modulo 2**256
3,03,SUB,3,NaN,"a, b",a - b,NaN,(u)int256 addition modulo 2**256
4,04,DIV,5,NaN,"a, b",a // b,NaN,uint256 division
5,05,SDIV,5,NaN,"a, b",a // b,NaN,Int256 division
6,06,MOD,5,NaN,"a, b",a % b,NaN,uint256 modulus
7,07,SMOD,5,NaN,"a, b",a % b,NaN,Int256 modulus
8,08,ADDMOD,8,NaN,"a, b, N",(a + b) % N,NaN,(u)int256 addition modulo N
9,09,MULMOD,8,NaN,"a, b, N",(a * b) % N,NaN,(u)int256 multiplication modulo N
10,0A,EXP,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a1-exp,"a, b",a ** b,NaN,uint256 exponentiation modulo 2**256
11,0B,SIGNEXTEND,5,NaN,"b, x","SIGNEXTEND(x, b)",NaN,Sign extend x from (b+1) bytes to 32 bytes
12,0C-0F,invalid,NaN,NaN,NaN,NaN,NaN,NaN
13,10,LT,3,NaN,"a, b",a < b,NaN,uint256 less-than
14,11,GT,3,NaN,"a, b",a > b,NaN,uint256 greater-than
15,12,SLT,3,NaN,"a, b",a < b,NaN,Int256 less-than
16,13,SGT,3,NaN,"a, b",a > b,NaN,Int256 greater-than
17,14,EQ,3,NaN,"a, b",a == b,NaN,(u)int256 equality
18,15,ISZERO,3,NaN,a,a == 0,NaN,(u)int256 iszero
19,16,AND,3,NaN,"a, b",a && b,NaN,Bitwise AND
20,17,OR,3,NaN,"a, b",a \|\| b,NaN,Bitwise OR
21,18,XOR,3,NaN,"a, b",a ^ b,NaN,Bitwise XOR
22,19,NOT,3,NaN,a,~a,NaN,Bitwise NOT
23,1A,BYTE,3,NaN,"i, x",(x >> (248 - i * 8)) && 0xFF,NaN,"Ith byte of (u)int256 x, from the left"
24,1B,SHL,3,NaN,"shift, val",val << shift,NaN,Shift left
25,1C,SHR,3,NaN,"shift, val",val >> shift,NaN,Logical shift right
26,1D,SAR,3,NaN,"shift, val",val >> shift,NaN,Arithmetic shift right
27,1E-1F,invalid,NaN,NaN,NaN,NaN,NaN,NaN
28,20,KECCAK256,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a2-sha3,"ost, len",keccak256(mem[ost:ost+len-1]),NaN,Keccak256
29,21-2F,invalid,NaN,NaN,NaN,NaN,NaN,NaN
30,30,ADDRESS,2,NaN,.,address(this),NaN,Address of executing contract
31,31,BALANCE,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a5-balance-extcodesize-extcodehash,addr,addr.balance,NaN,"Balance, in wei"
32,32,ORIGIN,2,NaN,.,tx.origin,NaN,Address that originated the tx
33,33,CALLER,2,NaN,.,msg.sender,NaN,Address of msg sender
34,34,CALLVALUE,2,NaN,.,msg.value,NaN,"Msg value, in wei"
35,35,CALLDATALOAD,3,NaN,idx,msg.data[idx:idx+32],NaN,Read word from msg data at index idx
36,36,CALLDATASIZE,2,NaN,.,len(msg.data),NaN,"Length of msg data, in bytes"
37,37,CALLDATACOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a3-copy-operations,"dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := msg.data[ost:ost+len-1],Copy msg data
38,38,CODESIZE,2,NaN,.,len(this.code),NaN,"Length of executing contract's code, in bytes"
39,39,CODECOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a3-copy-operations,"dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := this.code[ost:ost+len-1],Copy executing contract's bytecode
40,3A,GASPRICE,2,NaN,.,tx.gasprice,NaN,"Gas price of tx, in wei per unit gas **"
41,3B,EXTCODESIZE,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a5-balance-extcodesize-extcodehash,addr,len(addr.code),NaN,"Size of code at addr, in bytes"
42,3C,EXTCODECOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a4-extcodecopy,"addr, dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := addr.code[ost:ost+len-1],Copy code from addr
43,3D,RETURNDATASIZE,2,NaN,.,size,NaN,"Size of returned data from last external call, in bytes"
44,3E,RETURNDATACOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a3-copy-operations,"dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := returndata[ost:ost+len-1],Copy returned data from last external call
45,3F,EXTCODEHASH,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a5-balance-extcodesize-extcodehash,addr,hash,NaN,Hash = addr.exists ? keccak256(addr.code) : 0
46,40,BLOCKHASH,20,NaN,blockNum,blockHash(blockNum),NaN,NaN
47,41,COINBASE,2,NaN,.,block.coinbase,NaN,Address of miner of current block
48,42,TIMESTAMP,2,NaN,.,block.timestamp,NaN,Timestamp of current block
49,43,NUMBER,2,NaN,.,block.number,NaN,Number of current block
50,44,PREVRANDAO,2,NaN,.,randomness beacon,NaN,Randomness beacon
51,45,GASLIMIT,2,NaN,.,block.gaslimit,NaN,Gas limit of current block
52,46,CHAINID,2,NaN,.,chain_id,NaN,Push current chain id onto stack
53,47,SELFBALANCE,5,NaN,.,address(this).balance,NaN,"Balance of executing contract, in wei"
54,48,BASEFEE,2,NaN,.,block.basefee,NaN,Base fee of current block
55,49,BLOBHASH,3,NaN,idx,tx.blob_versioned_hashes[idx],NaN,EIP-4844
56,4A,BLOBBASEFEE,2,NaN,.,block.blobbasefee,NaN,Blob base fee of current block (EIP-7516)
57,4B-4F,invalid,NaN,NaN,NaN,NaN,NaN,NaN
58,50,POP,2,NaN,_anon,.,NaN,Remove item from top of stack and discard it
59,51,MLOAD,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion,ost,mem[ost:ost+32],NaN,Read word from memory at offset ost
60,52,MSTORE,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion,"ost, val",.,mem[ost:ost+32] := val,Write a word to memory
61,53,MSTORE8,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion,"ost, val",.,mem[ost] := val && 0xFF,Write a single byte to memory
62,54,SLOAD,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a6-sload,key,storage[key],NaN,Read word from storage
63,55,SSTORE,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a7-sstore,"key, val",.,storage[key] := val,Write word to storage
64,56,JUMP,8,NaN,dst,.,NaN,$pc := dst mark that pc is only assigned if dst is a valid jumpdest
65,57,JUMPI,10,NaN,"dst, condition",.,NaN,$pc := condition ? dst : $pc + 1
66,58,PC,2,NaN,.,$pc,NaN,Program counter
67,59,MSIZE,2,NaN,.,len(mem),NaN,"Size of memory in current execution context, in bytes"
68,5A,GAS,2,NaN,.,gasRemaining,NaN,NaN
69,5B,JUMPDEST,1,NaN,NaN,NaN,mark valid jump destination,A valid jump destination for example a jump destination not inside the push data
70,5C,TLOAD,100,NaN,key,tstorage[key],NaN,Read word from transient storage (EIP-1153)
71,5D,TSTORE,100,NaN,"key, val",.,tstorage[key] := val,Write word to transient storage (EIP-1153)
72,5E,MCOPY,3 + 3 * words,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion,"dstOst, ost, len",.,mem[dstOst] := mem[ost:ost+len],Copy memory from one area to another (EIP-5656)
73,5F,PUSH0,2,NaN,.,uint8,NaN,Push the constant value 0 onto stack
74,60,PUSH1,3,NaN,.,uint8,NaN,Push 1-byte value onto stack
75,61,PUSH2,3,NaN,.,uint16,NaN,Push 2-byte value onto stack
76,62,PUSH3,3,NaN,.,uint24,NaN,Push 3-byte value onto stack
77,63,PUSH4,3,NaN,.,uint32,NaN,Push 4-byte value onto stack
78,64,PUSH5,3,NaN,.,uint40,NaN,Push 5-byte value onto stack
79,65,PUSH6,3,NaN,.,uint48,NaN,Push 6-byte value onto stack
80,66,PUSH7,3,NaN,.,uint56,NaN,Push 7-byte value onto stack
81,67,PUSH8,3,NaN,.,uint64,NaN,Push 8-byte value onto stack
82,68,PUSH9,3,NaN,.,uint72,NaN,Push 9-byte value onto stack
83,69,PUSH10,3,NaN,.,uint80,NaN,Push 10-byte value onto stack
84,6A,PUSH11,3,NaN,.,uint88,NaN,Push 11-byte value onto stack
85,6B,PUSH12,3,NaN,.,uint96,NaN,Push 12-byte value onto stack
86,6C,PUSH13,3,NaN,.,uint104,NaN,Push 13-byte value onto stack
87,6D,PUSH14,3,NaN,.,uint112,NaN,Push 14-byte value onto stack
88,6E,PUSH15,3,NaN,.,uint120,NaN,Push 15-byte value onto stack
89,6F,PUSH16,3,NaN,.,uint128,NaN,Push 16-byte value onto stack
90,70,PUSH17,3,NaN,.,uint136,NaN,Push 17-byte value onto stack
91,71,PUSH18,3,NaN,.,uint144,NaN,Push 18-byte value onto stack
92,72,PUSH19,3,NaN,.,uint152,NaN,Push 19-byte value onto stack
93,73,PUSH20,3,NaN,.,uint160,NaN,Push 20-byte value onto stack
94,74,PUSH21,3,NaN,.,uint168,NaN,Push 21-byte value onto stack
95,75,PUSH22,3,NaN,.,uint176,NaN,Push 22-byte value onto stack
96,76,PUSH23,3,NaN,.,uint184,NaN,Push 23-byte value onto stack
97,77,PUSH24,3,NaN,.,uint192,NaN,Push 24-byte value onto stack
98,78,PUSH25,3,NaN,.,uint200,NaN,Push 25-byte value onto stack
99,79,PUSH26,3,NaN,.,uint208,NaN,Push 26-byte value onto stack
100,7A,PUSH27,3,NaN,.,uint216,NaN,Push 27-byte value onto stack
101,7B,PUSH28,3,NaN,.,uint224,NaN,Push 28-byte value onto stack
102,7C,PUSH29,3,NaN,.,uint232,NaN,Push 29-byte value onto stack
103,7D,PUSH30,3,NaN,.,uint240,NaN,Push 30-byte value onto stack
104,7E,PUSH31,3,NaN,.,uint248,NaN,Push 31-byte value onto stack
105,7F,PUSH32,3,NaN,.,uint256,NaN,Push 32-byte value onto stack
106,80,DUP1,3,NaN,a,"a, a",NaN,Clone 1st value on stack
107,81,DUP2,3,NaN,"_, a","a, _, a",NaN,Clone 2nd value on stack
108,82,DUP3,3,NaN,"_, _, a","a, _, _, a",NaN,Clone 3rd value on stack
109,83,DUP4,3,NaN,"_, _, _, a","a, _, _, _, a",NaN,Clone 4th value on stack
110,84,DUP5,3,NaN,"..., a","a, ..., a",NaN,Clone 5th value on stack
111,85,DUP6,3,NaN,"..., a","a, ..., a",NaN,Clone 6th value on stack
112,86,DUP7,3,NaN,"..., a","a, ..., a",NaN,Clone 7th value on stack
113,87,DUP8,3,NaN,"..., a","a, ..., a",NaN,Clone 8th value on stack
114,88,DUP9,3,NaN,"..., a","a, ..., a",NaN,Clone 9th value on stack
115,89,DUP10,3,NaN,"..., a","a, ..., a",NaN,Clone 10th value on stack
116,8A,DUP11,3,NaN,"..., a","a, ..., a",NaN,Clone 11th value on stack
117,8B,DUP12,3,NaN,"..., a","a, ..., a",NaN,Clone 12th value on stack
118,8C,DUP13,3,NaN,"..., a","a, ..., a",NaN,Clone 13th value on stack
119,8D,DUP14,3,NaN,"..., a","a, ..., a",NaN,Clone 14th value on stack
120,8E,DUP15,3,NaN,"..., a","a, ..., a",NaN,Clone 15th value on stack
121,8F,DUP16,3,NaN,"..., a","a, ..., a",NaN,Clone 16th value on stack
122,90,SWAP1,3,NaN,"a, b","b, a",NaN,NaN
123,91,SWAP2,3,NaN,"a, _, b","b, _, a",NaN,NaN
124,92,SWAP3,3,NaN,"a, _, _, b","b, _, _, a",NaN,NaN
125,93,SWAP4,3,NaN,"a, _, _, _, b","b, _, _, _, a",NaN,NaN
126,94,SWAP5,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
127,95,SWAP6,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
128,96,SWAP7,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
129,97,SWAP8,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
130,98,SWAP9,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
131,99,SWAP10,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
132,9A,SWAP11,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
133,9B,SWAP12,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
134,9C,SWAP13,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
135,9D,SWAP14,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
136,9E,SWAP15,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
137,9F,SWAP16,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
138,A0,LOG0,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a8-log-operations,"ost, len",.,NaN,LOG0(memory[ost:ost+len-1])
139,A1,LOG1,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a8-log-operations,"ost, len, topic0",.,NaN,"LOG1(memory[ost:ost+len-1], topic0)"
140,A2,LOG2,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a8-log-operations,"ost, len, topic0, topic1",.,NaN,"LOG2(memory[ost:ost+len-1], topic0, topic1)"
141,A3,LOG3,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a8-log-operations,"ost, len, topic0, topic1, topic2",.,NaN,"LOG3(memory[ost:ost+len-1], topic0, topic1, topic2)"
142,A4,LOG4,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a8-log-operations,"ost, len, topic0, topic1, topic2, topic3",.,NaN,"LOG4(memory[ost:ost+len-1], topic0, topic1, topic2, topic3)"
143,A5-EF,invalid,NaN,NaN,NaN,NaN,NaN,NaN
144,F0,CREATE,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a9-create-operations,"val, ost, len",addr,NaN,"Addr = keccak256(rlp([address(this), this.nonce]))"
145,F1,CALL,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#aa-call-operations,"gas, addr, val, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] := returndata,NaN
146,F2,CALLCODE,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#aa-call-operations,"gas, addr, val, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] = returndata,"Same as DELEGATECALL, but does not propagate original msg.sender and msg.value"
147,F3,RETURN,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion,"ost, len",.,NaN,Return mem[ost:ost+len-1]
148,F4,DELEGATECALL,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#aa-call-operations,"gas, addr, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] := returndata,NaN
149,F5,CREATE2,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a9-create-operations,"val, ost, len, salt",addr,NaN,Addr = keccak256(0xff ++ address(this) ++ salt ++ keccak256(mem[ost:ost+len-1]))[12:]
150,F6-F9,invalid,NaN,NaN,NaN,NaN,NaN,NaN
151,FA,STATICCALL,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#aa-call-operations,"gas, addr, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] := returndata,NaN
152,FB-FC,invalid,NaN,NaN,NaN,NaN,NaN,NaN
153,FD,REVERT,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion,"ost, len",.,NaN,Revert(mem[ost:ost+len-1])
154,FE,INVALID,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#af-invalid,NaN,NaN,NaN,Designated invalid opcode - EIP-141
155,FF,SELFDESTRUCT,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#ab-selfdestruct,addr,.,NaN,Sends all ETH to addr; if executed in the same transaction as a contract was created it destroys the contract

In [3]:
# Merge Push entries
push = source.copy()
pushes = push[push["Mnemonic"].apply(lambda v: "PUSH" in v and v != "PUSH0")]
first = pushes.iloc[0]
last = pushes.iloc[-1]
merged = first.copy()
merged.update(
    pd.Series(
        {
            "Opcode": str(first["Opcode"]) + ".." + str(last["Opcode"]),
            "Mnemonic": "PUSH[n]",
            "Output": "uint[8*n]",
            "Notes": "push n-byte value onto stack, where n is between 1..32 inclusive",
        }
    )
)
push.drop(index=list(pushes.index), inplace=True)
push.loc[len(push.index)] = merged
push.reset_index(inplace=True, drop=True)
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(push)

,Opcode,Mnemonic,Gas Constant,Gas Dynamic,Inputs,Output,Mem / Storage,Notes
0,00,STOP,0,NaN,NaN,NaN,NaN,Halt execution
1,01,ADD,3,NaN,"a, b",a + b,NaN,(u)int256 addition modulo 2**256
2,02,MUL,5,NaN,"a, b",a * b,NaN,(u)int256 multiplication modulo 2**256
3,03,SUB,3,NaN,"a, b",a - b,NaN,(u)int256 addition modulo 2**256
4,04,DIV,5,NaN,"a, b",a // b,NaN,uint256 division
5,05,SDIV,5,NaN,"a, b",a // b,NaN,Int256 division
6,06,MOD,5,NaN,"a, b",a % b,NaN,uint256 modulus
7,07,SMOD,5,NaN,"a, b",a % b,NaN,Int256 modulus
8,08,ADDMOD,8,NaN,"a, b, N",(a + b) % N,NaN,(u)int256 addition modulo N
9,09,MULMOD,8,NaN,"a, b, N",(a * b) % N,NaN,(u)int256 multiplication modulo N
10,0A,EXP,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"a, b",a ** b,NaN,uint256 exponentiation modulo 2**256
11,0B,SIGNEXTEND,5,NaN,"b, x","SIGNEXTEND(x, b)",NaN,Sign extend x from (b+1) bytes to 32 bytes
12,0C-0F,invalid,NaN,NaN,NaN,NaN,NaN,NaN
13,10,LT,3,NaN,"a, b",a < b,NaN,uint256 less-than
14,11,GT,3,NaN,"a, b",a > b,NaN,uint256 greater-than
15,12,SLT,3,NaN,"a, b",a < b,NaN,Int256 less-than
16,13,SGT,3,NaN,"a, b",a > b,NaN,Int256 greater-than
17,14,EQ,3,NaN,"a, b",a == b,NaN,(u)int256 equality
18,15,ISZERO,3,NaN,a,a == 0,NaN,(u)int256 iszero
19,16,AND,3,NaN,"a, b",a && b,NaN,Bitwise AND
20,17,OR,3,NaN,"a, b",a \|\| b,NaN,Bitwise OR
21,18,XOR,3,NaN,"a, b",a ^ b,NaN,Bitwise XOR
22,19,NOT,3,NaN,a,~a,NaN,Bitwise NOT
23,1A,BYTE,3,NaN,"i, x",(x >> (248 - i * 8)) && 0xFF,NaN,"Ith byte of (u)int256 x, from the left"
24,1B,SHL,3,NaN,"shift, val",val << shift,NaN,Shift left
25,1C,SHR,3,NaN,"shift, val",val >> shift,NaN,Logical shift right
26,1D,SAR,3,NaN,"shift, val",val >> shift,NaN,Arithmetic shift right
27,1E-1F,invalid,NaN,NaN,NaN,NaN,NaN,NaN
28,20,KECCAK256,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len",keccak256(mem[ost:ost+len-1]),NaN,Keccak256
29,21-2F,invalid,NaN,NaN,NaN,NaN,NaN,NaN
30,30,ADDRESS,2,NaN,.,address(this),NaN,Address of executing contract
31,31,BALANCE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,addr,addr.balance,NaN,"Balance, in wei"
32,32,ORIGIN,2,NaN,.,tx.origin,NaN,Address that originated the tx
33,33,CALLER,2,NaN,.,msg.sender,NaN,Address of msg sender
34,34,CALLVALUE,2,NaN,.,msg.value,NaN,"Msg value, in wei"
35,35,CALLDATALOAD,3,NaN,idx,msg.data[idx:idx+32],NaN,Read word from msg data at index idx
36,36,CALLDATASIZE,2,NaN,.,len(msg.data),NaN,"Length of msg data, in bytes"
37,37,CALLDATACOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := msg.data[ost:ost+l...,Copy msg data
38,38,CODESIZE,2,NaN,.,len(this.code),NaN,"Length of executing contract's code, in bytes"
39,39,CODECOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := this.code[ost:ost+...,Copy executing contract's bytecode
40,3A,GASPRICE,2,NaN,.,tx.gasprice,NaN,"Gas price of tx, in wei per unit gas **"
41,3B,EXTCODESIZE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,addr,len(addr.code),NaN,"Size of code at addr, in bytes"
42,3C,EXTCODECOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"addr, dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := addr.code[ost:ost+...,Copy code from addr
43,3D,RETURNDATASIZE,2,NaN,.,size,NaN,"Size of returned data from last external call,..."
44,3E,RETURNDATACOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := returndata[ost:ost...,Copy returned data from last external call
45,3F,EXTCODEHASH,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,addr,hash,NaN,Hash = addr.exists ? keccak256(addr.code) : 0
46,40,BLOCKHASH,20,NaN,blockNum,blockHash(blockNum),NaN,NaN
47,41,COINBASE,2,NaN,.,block.coinbase,NaN,Address of miner of current block
48,42,TIMESTAMP,2,NaN,.,block.timestamp,NaN,Timestamp of current block
49,43,NUMBER,2,NaN,.,block.number,NaN,Number of current block
50,44,PREVRANDAO,2,NaN,.,randomness beacon,NaN,Randomness beacon
51,45,GASLIMIT,2,NaN,.,block.gaslimit,NaN,Gas limit of current block
52,46,CHAINID,2,NaN,.,chain_id,NaN,Push current chain id onto stack
53,47,SELFBALANCE,5,NaN,.,address(this).balance,NaN,"Balance of executing contract, in wei"
54,48,BASEFEE,2,NaN,.,block.basefee,NaN,Base fee of current block
55,49,BLOBHASH,3,NaN,idx,tx.blob_versioned_hashes[idx],NaN,EIP-4844
56,4A,BLOBBASEFEE,2,NaN,.,block.blobbasefee,NaN,Blob base fee of current block (EIP-7516)
57,4B-4F,invalid,NaN,NaN,NaN,NaN,NaN,NaN
58,50,POP,2,NaN,_anon,.,NaN,Remove item from top of stack and discard it
59,51,MLOAD,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,ost,mem[ost:ost+32],NaN,Read word from memory at offset ost
60,52,MSTORE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, val",.,mem[ost:ost+32] := val,Write a word to memory
61,53,MSTORE8,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, val",.,mem[ost] := val && 0xFF,Write a single byte to memory
62,54,SLOAD,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,key,storage[key],NaN,Read word from storage
63,55,SSTORE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"key, val",.,storage[key] := val,Write word to storage
64,56,JUMP,8,NaN,dst,.,NaN,$pc := dst mark that pc is only assigned if ds...
65,57,JUMPI,10,NaN,"dst, condition",.,NaN,$pc := condition ? dst : $pc + 1
66,58,PC,2,NaN,.,$pc,NaN,Program counter
67,59,MSIZE,2,NaN,.,len(mem),NaN,"Size of memory in current execution context, i..."
68,5A,GAS,2,NaN,.,gasRemaining,NaN,NaN
69,5B,JUMPDEST,1,NaN,NaN,NaN,mark valid jump destination,A valid jump destination for example a jump de...
70,5C,TLOAD,100,NaN,key,tstorage[key],NaN,Read word from transient storage (EIP-1153)
71,5D,TSTORE,100,NaN,"key, val",.,tstorage[key] := val,Write word to transient storage (EIP-1153)
72,5E,MCOPY,3 + 3 * words,https://github.com/wolflo/evm-opcodes/blob/mai...,"dstOst, ost, len",.,mem[dstOst] := mem[ost:ost+len],Copy memory from one area to another (EIP-5656)
73,5F,PUSH0,2,NaN,.,uint8,NaN,Push the constant value 0 onto stack
74,80,DUP1,3,NaN,a,"a, a",NaN,Clone 1st value on stack
75,81,DUP2,3,NaN,"_, a","a, _, a",NaN,Clone 2nd value on stack
76,82,DUP3,3,NaN,"_, _, a","a, _, _, a",NaN,Clone 3rd value on stack
77,83,DUP4,3,NaN,"_, _, _, a","a, _, _, _, a",NaN,Clone 4th value on stack
78,84,DUP5,3,NaN,"..., a","a, ..., a",NaN,Clone 5th value on stack
79,85,DUP6,3,NaN,"..., a","a, ..., a",NaN,Clone 6th value on stack
80,86,DUP7,3,NaN,"..., a","a, ..., a",NaN,Clone 7th value on stack
81,87,DUP8,3,NaN,"..., a","a, ..., a",NaN,Clone 8th value on stack
82,88,DUP9,3,NaN,"..., a","a, ..., a",NaN,Clone 9th value on stack
83,89,DUP10,3,NaN,"..., a","a, ..., a",NaN,Clone 10th value on stack
84,8A,DUP11,3,NaN,"..., a","a, ..., a",NaN,Clone 11th value on stack
85,8B,DUP12,3,NaN,"..., a","a, ..., a",NaN,Clone 12th value on stack
86,8C,DUP13,3,NaN,"..., a","a, ..., a",NaN,Clone 13th value on stack
87,8D,DUP14,3,NaN,"..., a","a, ..., a",NaN,Clone 14th value on stack
88,8E,DUP15,3,NaN,"..., a","a, ..., a",NaN,Clone 15th value on stack
89,8F,DUP16,3,NaN,"..., a","a, ..., a",NaN,Clone 16th value on stack
90,90,SWAP1,3,NaN,"a, b","b, a",NaN,NaN
91,91,SWAP2,3,NaN,"a, _, b","b, _, a",NaN,NaN
92,60..7F,PUSH[n],3,NaN,.,uint[8*n],NaN,"push n-byte value onto stack, where n is betwe..."
93,93,SWAP4,3,NaN,"a, _, _, _, b","b, _, _, _, a",NaN,NaN
94,94,SWAP5,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
95,95,SWAP6,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
96,96,SWAP7,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
97,97,SWAP8,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
98,98,SWAP9,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
99,99,SWAP10,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
100,9A,SWAP11,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
101,9B,SWAP12,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
102,9C,SWAP13,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
103,9D,SWAP14,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
104,9E,SWAP15,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
105,9F,SWAP16,3,NaN,"a, ..., b","b, ..., a",NaN,NaN
106,A0,LOG0,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len",.,NaN,LOG0(memory[ost:ost+len-1])
107,A1,LOG1,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len, topic0",.,NaN,"LOG1(memory[ost:ost+len-1], topic0)"
108,A2,LOG2,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len, topic0, topic1",.,NaN,"LOG2(memory[ost:ost+len-1], topic0, topic1)"
109,A3,LOG3,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len, topic0, topic1, topic2",.,NaN,"LOG3(memory[ost:ost+len-1], topic0, topic1, to..."
110,A4,LOG4,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len, topic0, topic1, topic2, topic3",.,NaN,"LOG4(memory[ost:ost+len-1], topic0, topic1, to..."
111,A5-EF,invalid,NaN,NaN,NaN,NaN,NaN,NaN
112,F0,CREATE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"val, ost, len",addr,NaN,"Addr = keccak256(rlp([address(this), this.nonc..."
113,F1,CALL,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"gas, addr, val, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] := returndata,NaN
114,F2,CALLCODE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"gas, addr, val, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] = returndata,"Same as DELEGATECALL, but does not propagate o..."
115,F3,RETURN,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len",.,NaN,Return mem[ost:ost+len-1]
116,F4,DELEGATECALL,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"gas, addr, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] := returndata,NaN
117,F5,CREATE2,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"val, ost, len, salt",addr,NaN,Addr = keccak256(0xff ++ address(this) ++ salt...
118,F6-F9,invalid,NaN,NaN,NaN,NaN,NaN,NaN
119,FA,STATICCALL,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"gas, addr, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] := returndata,NaN
120,FB-FC,invalid,NaN,NaN,NaN,NaN,NaN,NaN
121,FD,REVERT,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len",.,NaN,Revert(mem[ost:ost+len-1])
122,FE,INVALID,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,NaN,NaN,NaN,Designated invalid opcode - EIP-141
123,FF,SELFDESTRUCT,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,addr,.,NaN,Sends all ETH to addr; if executed in the same...

In [4]:
swap = push.copy()
swaps = swap[swap["Mnemonic"].str.contains("SWAP", case=False)].copy()
first = swaps.iloc[0]
last = swaps.iloc[-1]
swaps["Inputs"] = last["Inputs"]
swaps["Output"] = last["Output"]
merged = last.copy()
merged.update(
    pd.Series(
        {
            "Opcode": str(first["Opcode"]) + ".." + str(last["Opcode"]),
            "Mnemonic": "SWAP[n]",
            "Notes": "swap top of the stack with the nth item",
        }
    )
)
swap.drop(index=swaps.index, inplace=True)
swap.reset_index(inplace=True, drop=True)
swap.loc[len(swap.index)] = merged
display(swap)

,Opcode,Mnemonic,Gas Constant,Gas Dynamic,Inputs,Output,Mem / Storage,Notes
0,00,STOP,0,NaN,NaN,NaN,NaN,Halt execution
1,01,ADD,3,NaN,"a, b",a + b,NaN,(u)int256 addition modulo 2**256
2,02,MUL,5,NaN,"a, b",a * b,NaN,(u)int256 multiplication modulo 2**256
3,03,SUB,3,NaN,"a, b",a - b,NaN,(u)int256 addition modulo 2**256
4,04,DIV,5,NaN,"a, b",a // b,NaN,uint256 division
...,...,...,...,...,...,...,...,...
105,FB-FC,invalid,NaN,NaN,NaN,NaN,NaN,NaN
106,FD,REVERT,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len",.,NaN,Revert(mem[ost:ost+len-1])
107,FE,INVALID,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,NaN,NaN,NaN,Designated invalid opcode - EIP-141
108,FF,SELFDESTRUCT,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,addr,.,NaN,Sends all ETH to addr; if executed in the same...
109,90..9F,SWAP[n],3,NaN,"a, ..., b","b, ..., a",NaN,swap top of the stack with the nth item

In [5]:
dup = swap.copy()
dups = dup[dup["Mnemonic"].str.contains("DUP")].copy()
first = dups.iloc[0]
last = dups.iloc[-1]
merged = last.copy()
merged.update(
    pd.Series(
        {
            "Mnemonic": "DUP[n]",
            "Opcode": str(first["Opcode"]) + ".." + str(last["Opcode"]),
            "Inputs": last["Inputs"],
            "Output": last["Output"],
            "Notes": "clone nth value to the top of the stack",
        }
    )
)
dup.drop(index=dups.index, inplace=True)
dup.reset_index(inplace=True, drop=True)
dup.loc[len(dup.index)] = merged

with pd.option_context(*options):
    display(dup[dup["Mnemonic"] == "SLOAD"])

,Opcode,Mnemonic,Gas Constant,Gas Dynamic,Inputs,Output,Mem / Storage,Notes
62,54,SLOAD,NaN,https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a6-sload,key,storage[key],NaN,Read word from storage

In [6]:
# full_url = dup.iloc[-3]["Gas Dynamic"]
# gas_url = re.sub(r"#.*", "", full_url)
# response = get(gas_url)
# if response.status_code != 200:
#     raise RuntimeError("Failed fetch")
with open("../../../assets/evm/gas-costs.html", "r") as f:
    response = f.read()
page = BeautifulSoup(response, "html.parser")
page

<article class="markdown-body entry-content container-lg" itemprop="text">
<div class="markdown-heading" dir="auto">
<h1 class="heading-element" dir="auto" tabindex="-1">Appendix - Dynamic Gas Costs</h1><a aria-label="Permalink: Appendix - Dynamic Gas Costs" class="anchor" href="#appendix---dynamic-gas-costs" id="user-content-appendix---dynamic-gas-costs"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div>
<div class="markdown-heading" dir="auto">
<h3 class="heading-element" dir="auto" tabindex="-1">A0-0: Intrinsic Gas</h3><a aria-label="Permalink: A0-0: Intrinsic Gas" class="anchor" href="#a0-0-intrinsic-gas" id="user-content-a0-0-intrinsic-gas"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div>
<p dir="auto">Intrinsic gas is the amount of gas paid prior to execution of a transaction.
    That is, the gas paid by the initiator of a transaction, which will always be an externally-owned account, before
    any state updates are made or any code is executed.</p>
<p dir="auto">Gas Calculation:</p>
<ul dir="auto">
<li><code>gas_cost = 21000</code>: base cost</li>
<li><strong>If</strong> <code>tx.to == null</code> (contract creation tx):
      <ul dir="auto">
<li><code>gas_cost += 32000</code></li>
</ul>
</li>
<li><code>gas_cost += 4 * bytes_zero</code>: gas added to base cost for every zero byte of memory data</li>
<li><code>gas_cost += 16 * bytes_nonzero</code>: gas added to base cost for every nonzero byte of memory data</li>
</ul>
<div class="markdown-heading" dir="auto">
<h3 class="heading-element" dir="auto" tabindex="-1">A0-1: Memory Expansion</h3><a aria-label="Permalink: A0-1: Memory Expansion" class="anchor" href="#a0-1-memory-expansion" id="user-content-a0-1-memory-expansion"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div>
<p dir="auto">An additional gas cost is paid by any operation that expands the memory that is in use.
    This memory expansion cost is dependent on the existing memory size and is <code>0</code> if the operation does not
    reference a memory address higher than the existing highest referenced memory address.
    A reference is any read, write, or other usage of memory (such as in a <code>CALL</code>).</p>
<p dir="auto">Terms:</p>
<ul dir="auto">
<li><code>new_mem_size</code>: the highest referenced memory address after the operation in question (in bytes)</li>
<li><code>new_mem_size_words = (new_mem_size + 31) // 32</code>: number of (32-byte) words required for memory after
      the operation in question</li>
<li><code><em>C<sub>mem</sub>(machine_state)</em></code>: the memory cost function for a given machine state</li>
</ul>
<p dir="auto">Gas Calculation:</p>
<ul dir="auto">
<li><code>gas_cost = <em>C<sub>mem</sub>(new_state)</em> - <em>C<sub>mem</sub>(old_state)</em></code></li>
<li>
<code>gas_cost = (new_mem_size_words ^ 2 // 512) + (3 * new_mem_size_words) - <em>C<sub>mem</sub>(old_state)</em></code>
</li>
</ul>
<p dir="auto">Useful Notes:</p>
<ul dir="auto">
<li>The following opcodes incur a memory expansion cost in addition to their otherwise static gas cost:
      <code>RETURN</code>, <code>REVERT</code>, <code>MLOAD</code>, <code>MSTORE</code>, <code>MSTORE8</code>.</li>
<li>Referencing a zero length range does not require memory to be extended to the beginning of the range.</li>
<li>The memory cost function is linear up to 724 bytes of memory used, at which point additional memory costs
      substantially more.</li>
</ul>
<div class="markdown-heading" dir="auto">
<h3 class="heading-element" dir="auto" tabindex="-1">A0-2: Access Sets</h3><a aria-label="Permalink: A0-2: Access Sets" class="anchor" href="#a0-2-access-sets" id="user-content-a0-2-access-sets"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div>
<p dir="auto">As of <a href="https://eips.ethereum.org/EIPS/eip-2929" rel="nofollow">EIP-2929</a>, two
    transaction-wide access sets are maintained.
    These access sets keep track of which addresses and storage slots have already been touched within the current
    transaction.</p>
<ul dir="auto">
<li><code>touched_addresses : Set[Address]</code>
<ul dir="auto">
<li>a set where every element is an address</li>
<li>initialized to include <code>tx.origin</code>, <code>tx.to</code>*, and all precompiles</li>
<li>* For a contract creation transaction, <code>touched_addresses</code> is initialized to include the address
          of the created contract instead of <code>tx.to</code>, which is the zero address.</li>
</ul>
</li>
<li><code>touched_storage_slots : Set[(Address, Bytes32)]</code>
<ul dir="auto">
<li>a set where every element is a tuple, <code>(address, storage_key)</code></li>
<li>initialized to the empty set, <code>{}</code></li>
</ul>
</li>
</ul>
<p dir="auto">The access sets above are relevant for the following operations:</p>
<ul dir="auto">
<li>
<code>ADDRESS_TOUCHING_OPCODES := { EXTCODESIZE, EXTCODECOPY, EXTCODEHASH, BALANCE, CALL, CALLCODE, DELEGATECALL, STATICCALL, SELFDESTRUCT }</code>
</li>
<li><code>STORAGE_TOUCHING_OPCODES := { SLOAD, SSTORE }</code></li>
</ul>
<div class="markdown-heading" dir="auto">
<h4 class="heading-element" dir="auto" tabindex="-1">Updating the Access Sets</h4><a aria-label="Permalink: Updating the Access Sets" class="anchor" href="#updating-the-access-sets" id="user-content-updating-the-access-sets"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div>
<p dir="auto">When an address is the target of one of the <code>ADDRESS_TOUCHING_OPCODES</code>, the address is
    immediately added to the <code>touched_addresses</code> set.</p>
<ul dir="auto">
<li><code>touched addresses = touched_addresses ∪ { target_address }</code></li>
</ul>
<p dir="auto">When a storage slot is the target of one of the <code>STORAGE_TOUCHING_OPCODES</code>, the
    <code>(address, key)</code> pair is immediately added to the <code>touched_storage_slots</code> set.</p>
<ul dir="auto">
<li><code>touched_storage_slots = touched_storage_slots ∪ { (current_address, target_storage_key) }</code></li>
</ul>
<p dir="auto">Important Notes:</p>
<ul dir="auto">
<li>Adding duplicate elements to these sets is a no-op. Performant implementations will use a map with more
      complicated addition logic.</li>
<li>If an execution frame reverts, the access sets will return to the state they were in before the frame was
      entered.</li>
<li>Additions to the <code>touched_addresses</code> set for <code>*CALL</code> and <code>CREATE*</code> opcodes are
      made immediately <em>before</em> the new execution frames are entered, so any failure within a call or contract
      creation will not remove the target address of the failing <code>*CALL</code> or <code>CREATE*</code> from the
      <code>touched_addresses</code> set.
      Some tricky edge cases:
      <ul dir="auto">
<li>For <code>*CALL</code>, if the call fails for exceeding the maximum call depth or attempting to send more
          value than the balance of the current address, the target address remains in the
          <code>touched_addresses</code> set.</li>
<li>For <code>CREATE*</code>, if the contract creation fails for exceeding the maximum call depth or attempting
          to send more value than the balance of the current address, the address of the created contract does
          <strong>NOT</strong> remain in the <code>touched_addresses</code> set.</li>
<li>If a <code>CREATE*</code> operation fails for attempting to deploy a contract to a non-empty account, the
          address of the created contract remains in the <code>touched_addresses</code> set.</li>
</ul>
</li>
</ul>
<div class="markdown-heading" dir="auto">
<h4 class="heading-element" dir="auto" tabindex="-1">Pre-populating the Access Sets</h4><a aria-label="Permalink: Pre-populating the Access Sets" class="anchor" href="#pre-populating-the-access-sets" id="user-content-pre-populating-the-access-sets"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div>
<p dir="auto"><a href="https://eips.ethereum.org/EIPS/eip-2930" rel="nofollow">EIP-2930</a> introduced an optional
    access <em>list</em> that can be included as part of a transaction.
    This access list allows elements to be added to the <code>touched_addresses</code> and
    <code>touched_storage_slots</code> access <em>sets</em> before execution of a transaction begins.
    The cost for doing so is <code>2400</code> gas for each address added to <code>touched_addresses</code> and
    <code>1900</code> gas for each <code>(address, storage_key)</code> pair added to <code>touched_storage_slots</code>.
    This cost is charged at the same time as <a href="#a0-0-intrinsic-gas">intrinsic gas</a>.</p>
<p dir="auto">Important Notes:</p>
<ul dir="auto">
<li>No <code>(ADDR, storage_key)</code> pair can be added to <code>touched_storage_slots</code> without also adding
      <code>ADDR</code> to <code>touched_addresses</code>.</li>
<li>The access list may contain duplicates.
      The addition of a duplicate item to one of the access sets is a no-op, but the cost of addition is still charged.
    </li>
<li>Providing an access list with a transaction can yield a modest discount for each unique access, but this is not
      always the case.
      See <a href="https://hackmd.io/@fvictorio/gas-costs-after-berlin" rel="nofollow">@fvictorio/gas-costs-after-berlin</a> for a more complete discussion.</li>
</ul>
<div class="markdown-heading" dir="auto">
<h3 class="heading-element" dir="auto" tabindex="-1">A0-3: Gas Refunds</h3><a aria-label="Permalink: A0-3: Gas Refunds" class="anchor" href="#a0-3-gas-refunds" id="user-content-a0-3-gas-refunds"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div>
<p dir="auto">Originally intended to provide incentive for clearing unused state, the total <code>gas_refund</code> is
    tracked throughout the execution of a transaction.
    As of <a href="https://eips.ethereum.org/EIPS/eip-3529" rel="nofollow">EIP-3529</a>, <code>SSTORE</code> is the only
    operation that potentially provides a gas refund.</p>
<p dir="auto">The maximum refund for a transaction is capped at 1/5<sup>th</sup> the gas consumed for the entire
    transaction.</p>
<div class="snippet-clipboard-content notranslate position-relative overflow-auto">
<pre class="notranslate"><code>refund_amt := min(gas_refund, tx.gas_consumed // 5)
</code></pre>
<div class="zeroclipboard-container">
<clipboard-copy aria-label="Copy" class="ClipboardButton btn btn-invisible js-clipboard-copy m-2 p-0 d-flex flex-justify-center flex-items-center" data-copy-feedback="Copied!" data-tooltip-direction="w" role="button" tabindex="0" value="refund_amt := min(gas_refund, tx.gas_consumed // 5)">
<svg aria-hidden="true" class="octicon octicon-copy js-clipboard-copy-icon" data-view-component="true" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="M0 6.75C0 5.784.784 5 1.75 5h1.5a.75.75 0 0 1 0 1.5h-1.5a.25.25 0 0 0-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 0 0 .25-.25v-1.5a.75.75 0 0 1 1.5 0v1.5A1.75 1.75 0 0 1 9.25 16h-7.5A1.75 1.75 0 0 1 0 14.25Z">
</path>
<path d="M5 1.75C5 .784 5.784 0 6.75 0h7.5C15.216 0 16 .784 16 1.75v7.5A1.75 1.75 0 0 1 14.25 11h-7.5A1.75 1.75 0 0 1 5 9.25Zm1.75-.25a.25.25 0 0 0-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 0 0 .25-.25v-7.5a.25.25 0 0 0-.25-.25Z">
</path>
</svg>
<svg aria-hidden="true" class="octicon octicon-check js-clipboard-check-icon color-fg-success d-none" data-view-component="true" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="M13.78 4.22a.75.75 0 0 1 0 1.06l-7.25 7.25a.75.75 0 0 1-1.06 0L2.22 9.28a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018L6 10.94l6.72-6.72a.75.75 0 0 1 1.06 0Z">
</path>
</svg>
</clipboard-copy>
</div>
</div>
<p dir="auto">The gas consumed includes the <a href="#a0-0-intrinsic-gas">intrinsic gas</a>, the cost of <a href="#pre-populating-the-access-sets">pre-populating</a> the access sets, and the cost of any code execution.</p>
<p dir="auto">When a transaction is finalized, the gas used by the transaction is decreased by
    <code>refund_amt</code>.
    This effectively reimburses <code>refund_amt * tx.gasprice</code> to <code>tx.origin</code>, but it has
    the added effect of decreasing the impact of the transaction on the total gas consumed in the block (for purposes of
    determining the block gas limit).</p>
<p dir="auto">Because the gas refund is not applied until the end of a transaction, a nonzero refund will not affect
    whether or not a transaction results in an <code>OUT_OF_GAS</code> exception.</p>
<h1 dir="auto"></h1>
<div class="markdown-heading" dir="auto">
<h2 class="heading-element" dir="auto" tabindex="-1">A1: EXP</h2><a aria-label="Permalink: A1: EXP" class="anchor" href="#a1-exp" id="user-content-a1-exp"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div>
<p dir="auto">Terms:</p>
<ul dir="auto">
<li><code>byte_len_exponent</code>: the number of bytes in the exponent (exponent is <code>b</code> in the stack
      representation)</li>
</ul>
<p dir="auto">Gas Calculation:</p>
<ul dir="auto">
<li><code>gas_cost = 10 + 50 * byte_len_exponent</code></li>
</ul>
<div class="markdown-heading" dir="auto">
<h2 class="heading-element" dir="auto" tabindex="-1">A2: SHA3</h2><a aria-label="Permalink: A2: SHA3" class="anchor" href="#a2-sha3" id="user-content-a2-sha3"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div>
<p dir="auto">Terms:</p>
<ul dir="auto">
<li><code>data_size</code>: size of the message to hash in bytes (<code>len</code> in the stack representation)</li>
<li><code>data_size_words = (data_size + 31) // 32</code>: number of (32-byte) words in the message to hash</li>
<li><code>mem_expansion_cost</code>: the cost of any memory expansion required (see <a href="#a0-1-memory-expansion">A0-1</a>)</li>
</ul>
<p dir="auto">Gas Calculation:</p>
<ul dir="auto">
<li><code>gas_cost = 30 + 6 * data_size_words + mem_expansion_cost</code></li>
</ul>
<div class="markdown-heading" dir="auto">
<h2 class="heading-element" dir="auto" tabindex="-1">A3: *COPY Operations</h2><a aria-label="Permalink: A3: *COPY Operations" class="anchor" href="#a3-copy-operations" id="user-content-a3-copy-operations"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">

In [7]:
def new_section():
    return BeautifulSoup("", "html.parser")


def append_to_sections(header, section):
    href = header.a["href"][1:]
    section_sanitized = section.svg.decompose()
    section.a["href"] = (
        "https://github.com/wolflo/evm-opcodes/blob/main/gas.md"
    ) + section.a["href"]
    sections[href] = {
        "header": header,
        "section": section,
        "href": href,
        "sections_pretty": section.prettify(),
    }


article = deepcopy(page.article)
sections = {}
section = new_section()
header = article.find(class_="markdown-heading")

for child in article.children:
    if child.name is None:
        continue
    if child.get("class") == ["markdown-heading"]:
        if child.find("h3") is not None or child.find("h2") is not None:
            append_to_sections(header, section)
            section = new_section()
            section.append(child)
            header = child
            continue
    section.append(child)
append_to_sections(header, section)

for key in sections.keys():
    print(key)
    print(sections[key]["section"])
    print("\n\n")

appendix---dynamic-gas-costs
<div class="markdown-heading" dir="auto">
<h1 class="heading-element" dir="auto" tabindex="-1">Appendix - Dynamic Gas Costs</h1><a aria-label="Permalink: Appendix - Dynamic Gas Costs" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#appendix---dynamic-gas-costs" id="user-content-appendix---dynamic-gas-costs"></a>
</div>



a0-0-intrinsic-gas
<div class="markdown-heading" dir="auto">
<h3 class="heading-element" dir="auto" tabindex="-1">A0-0: Intrinsic Gas</h3><a aria-label="Permalink: A0-0: Intrinsic Gas" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-0-intrinsic-gas" id="user-content-a0-0-intrinsic-gas"></a>
</div><p dir="auto">Intrinsic gas is the amount of gas paid prior to execution of a transaction.
    That is, the gas paid by the initiator of a transaction, which will always be an externally-owned account, before
    any state updates are made or any code is executed.</p><p dir="auto">Gas Calculation:</p><ul dir="auto">
<li><code>gas_cost = 21000</code>: base cost</li>
<li><strong>If</strong> <code>tx.to == null</code> (contract creation tx):
      <ul dir="auto">
<li><code>gas_cost += 32000</code></li>
</ul>
</li>
<li><code>gas_cost += 4 * bytes_zero</code>: gas added to base cost for every zero byte of memory data</li>
<li><code>gas_cost += 16 * bytes_nonzero</code>: gas added to base cost for every nonzero byte of memory data</li>
</ul>



a0-1-memory-expansion
<div class="markdown-heading" dir="auto">
<h3 class="heading-element" dir="auto" tabindex="-1">A0-1: Memory Expansion</h3><a aria-label="Permalink: A0-1: Memory Expansion" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion" id="user-content-a0-1-memory-expansion"></a>
</div><p dir="auto">An additional gas cost is paid by any operation that expands the memory that is in use.
    This memory expansion cost is dependent on the existing memory size and is <code>0</code> if the operation does not
    reference a memory address higher than the existing highest referenced memory address.
    A reference is any read, write, or other usage of memory (such as in a <code>CALL</code>).</p><p dir="auto">Terms:</p><ul dir="auto">
<li><code>new_mem_size</code>: the highest referenced memory address after the operation in question (in bytes)</li>
<li><code>new_mem_size_words = (new_mem_size + 31) // 32</code>: number of (32-byte) words required for memory after
      the operation in question</li>
<li><code><em>C<sub>mem</sub>(machine_state)</em></code>: the memory cost function for a given machine state</li>
</ul><p dir="auto">Gas Calculation:</p><ul dir="auto">
<li><code>gas_cost = <em>C<sub>mem</sub>(new_state)</em> - <em>C<sub>mem</sub>(old_state)</em></code></li>
<li>
<code>gas_cost = (new_mem_size_words ^ 2 // 512) + (3 * new_mem_size_words) - <em>C<sub>mem</sub>(old_state)</em></code>
</li>
</ul><p dir="auto">Useful Notes:</p><ul dir="auto">
<li>The following opcodes incur a memory expansion cost in addition to their otherwise static gas cost:
      <code>RETURN</code>, <code>REVERT</code>, <code>MLOAD</code>, <code>MSTORE</code>, <code>MSTORE8</code>.</li>
<li>Referencing a zero length range does not require memory to be extended to the beginning of the range.</li>
<li>The memory cost function is linear up to 724 bytes of memory used, at which point additional memory costs
      substantially more.</li>
</ul>



a0-2-access-sets
<div class="markdown-heading" dir="auto">
<h3 class="heading-element" dir="auto" tabindex="-1">A0-2: Access Sets</h3><a aria-label="Permalink: A0-2: Access Sets" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-2-access-sets" id="user-content-a0-2-access-sets"></a>
</div><p dir="auto">As of <a href="https://eips.ethereum.org/EIPS/eip-2929" rel="nofollow">EIP-2929</a>, two
    transaction-wide access sets are maintained.
    These access sets keep track of which addresses and storage slots have already been touched within the current
    transaction.</p><ul dir="auto">
<li><code>touched_addresses : Set[Address]</code>
<ul dir="auto">
<li>a set where every element is an address</li>
<li>initialized to include <code>tx.origin</code>, <code>tx.to</code>*, and all precompiles</li>
<li>* For a contract creation transaction, <code>touched_addresses</code> is initialized to include the address
          of the created contract instead of <code>tx.to</code>, which is the zero address.</li>
</ul>
</li>
<li><code>touched_storage_slots : Set[(Address, Bytes32)]</code>
<ul dir="auto">
<li>a set where every element is a tuple, <code>(address, storage_key)</code></li>
<li>initialized to the empty set, <code>{}</code></li>
</ul>
</li>
</ul><p dir="auto">The access sets above are relevant for the following operations:</p><ul dir="auto">
<li>
<code>ADDRESS_TOUCHING_OPCODES := { EXTCODESIZE, EXTCODECOPY, EXTCODEHASH, BALANCE, CALL, CALLCODE, DELEGATECALL, STATICCALL, SELFDESTRUCT }</code>
</li>
<li><code>STORAGE_TOUCHING_OPCODES := { SLOAD, SSTORE }</code></li>
</ul><div class="markdown-heading" dir="auto">
<h4 class="heading-element" dir="auto" tabindex="-1">Updating the Access Sets</h4><a aria-label="Permalink: Updating the Access Sets" class="anchor" href="#updating-the-access-sets" id="user-content-updating-the-access-sets"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div><p dir="auto">When an address is the target of one of the <code>ADDRESS_TOUCHING_OPCODES</code>, the address is
    immediately added to the <code>touched_addresses</code> set.</p><ul dir="auto">
<li><code>touched addresses = touched_addresses ∪ { target_address }</code></li>
</ul><p dir="auto">When a storage slot is the target of one of the <code>STORAGE_TOUCHING_OPCODES</code>, the
    <code>(address, key)</code> pair is immediately added to the <code>touched_storage_slots</code> set.</p><ul dir="auto">
<li><code>touched_storage_slots = touched_storage_slots ∪ { (current_address, target_storage_key) }</code></li>
</ul><p dir="auto">Important Notes:</p><ul dir="auto">
<li>Adding duplicate elements to these sets is a no-op. Performant implementations will use a map with more
      complicated addition logic.</li>
<li>If an execution frame reverts, the access sets will return to the state they were in before the frame was
      entered.</li>
<li>Additions to the <code>touched_addresses</code> set for <code>*CALL</code> and <code>CREATE*</code> opcodes are
      made immediately <em>before</em> the new execution frames are entered, so any failure within a call or contract
      creation will not remove the target address of the failing <code>*CALL</code> or <code>CREATE*</code> from the
      <code>touched_addresses</code> set.
      Some tricky edge cases:
      <ul dir="auto">
<li>For <code>*CALL</code>, if the call fails for exceeding the maximum call depth or attempting to send more
          value than the balance of the current address, the target address remains in the
          <code>touched_addresses</code> set.</li>
<li>For <code>CREATE*</code>, if the contract creation fails for exceeding the maximum call depth or attempting
          to send more value than the balance of the current address, the address of the created contract does
          <strong>NOT</strong> remain in the <code>touched_addresses</code> set.</li>
<li>If a <code>CREATE*</code> operation fails for attempting to deploy a contract to a non-empty account, the
          address of the created contract remains in the <code>touched_addresses</code> set.</li>
</ul>
</li>
</ul><div class="markdown-heading" dir="auto">
<h4 class="heading-element" dir="auto" tabindex="-1">Pre-populating the Access Sets</h4><a aria-label="Permalink: Pre-populating the Access Sets" class="anchor" href="#pre-populating-the-access-sets" id="user-content-pre-populating-the-access-sets"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z">
</path>
</svg></a>
</div><p dir="auto"><a href="https://eips.ethereum.org/EIPS/eip-2930" rel="nofollow">EIP-2930</a> introduced an optional
    access <em>list</em> that can be included as part of a transaction.
    This access list allows elements to be added to the <code>touched_addresses</code> and
    <code>touched_storage_slots</code> access <em>sets</em> before execution of a transaction begins.
    The cost for doing so is <code>2400</code> gas for each address added to <code>touched_addresses</code> and
    <code>1900</code> gas for each <code>(address, storage_key)</code> pair added to <code>touched_storage_slots</code>.
    This cost is charged at the same time as <a href="#a0-0-intrinsic-gas">intrinsic gas</a>.</p><p dir="auto">Important Notes:</p><ul dir="auto">
<li>No <code>(ADDR, storage_key)</code> pair can be added to <code>touched_storage_slots</code> without also adding
      <code>ADDR</code> to <code>touched_addresses</code>.</li>
<li>The access list may contain duplicates.
      The addition of a duplicate item to one of the access sets is a no-op, but the cost of addition is still charged.
    </li>
<li>Providing an access list with a transaction can yield a modest discount for each unique access, but this is not
      always the case.
      See <a href="https://hackmd.io/@fvictorio/gas-costs-after-berlin" rel="nofollow">@fvictorio/gas-costs-after-berlin</a> for a more complete discussion.</li>
</ul>



a0-3-gas-refunds
<div class="markdown-heading" dir="auto">
<h3 class="heading-element" dir="auto" tabindex="-1">A0-3: Gas Refunds</h3><a aria-label="Permalink: A0-3: Gas Refunds" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-3-gas-refunds" id="user-content-a0-3-gas-refunds"></a>
</div><p dir="auto">Originally intended to provide incentive for clearing unused state, the total <code>gas_refund</code> is
    tracked throughout the execution of a transaction.
    As of <a href="https://eips.ethereum.org/EIPS/eip-3529" rel="nofollow">EIP-3529</a>, <code>SSTORE</code> is the only
    operation that potentially provides a gas refund.</p><p dir="auto">The maximum refund for a transaction is capped at 1/5<sup>th</sup> the gas consumed for the entire
    transaction.</p><div class="snippet-clipboard-content notranslate position-relative overflow-auto">
<pre class="notranslate"><code>refund_amt := min(gas_refund, tx.gas_consumed // 5)
</code></pre>
<div class="zeroclipboard-container">
<clipboard-copy aria-label="Copy" class="ClipboardButton btn btn-invisible js-clipboard-copy m-2 p-0 d-flex flex-justify-center flex-items-center" data-copy-feedback="Copied!" data-tooltip-direction="w" role="button" tabindex="0" value="refund_amt := min(gas_refund, tx.gas_consumed // 5)">
<svg aria-hidden="true" class="octicon octicon-copy js-clipboard-copy-icon" data-view-component="true" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="M0 6.75C0 5.784.784 5 1.75 5h1.5a.75.75 0 0 1 0 1.5h-1.5a.25.25 0 0 0-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 0 0 .25-.25v-1.5a.75.75 0 0 1 1.5 0v1.5A1.75 1.75 0 0 1 9.25 16h-7.5A1.75 1.75 0 0 1 0 14.25Z">
</path>
<path d="M5 1.75C5 .784 5.784 0 6.75 0h7.5C15.216 0 16 .784 16 1.75v7.5A1.75 1.75 0 0 1 14.25 11h-7.5A1.75 1.75 0 0 1 5 9.25Zm1.75-.25a.25.25 0 0 0-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 0 0 .25-.25v-7.5a.25.25 0 0 0-.25-.25Z">
</path>
</svg>
<svg aria-hidden="true" class="octicon octicon-check js-clipboard-check-icon color-fg-success d-none" data-view-component="true" height="16" version="1.1" viewbox="0 0 16 16" width="16">
<path d="M13.78 4.22a.75.75 0 0 1 0 1.06l-7.25 7.25a.75.75 0 0 1-1.06 0L2.22 9.28a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018L6 10.94l6.72-6.72a.75.75 0 0 1 1.06 0Z">
</path>
</svg>
</clipboard-copy>
</div>
</div><p dir="auto">The gas consumed includes the <a href="#a0-0-intrinsic-gas">intrinsic gas</a>, the cost of <a href="#pre-populating-the-access-sets">pre-populating</a> the access sets, and the cost of any code execution.</p><p dir="auto">When a transaction is finalized, the gas used by the transaction is decreased by
    <code>refund_amt</code>.
    This effectively reimburses <code>refund_amt * tx.gasprice</code> to <code>tx.origin</code>, but it has
    the added effect of decreasing the impact of the transaction on the total gas consumed in the block (for purposes of
    determining the block gas limit).</p><p dir="auto">Because the gas refund is not applied until the end of a transaction, a nonzero refund will not affect
    whether or not a transaction results in an <code>OUT_OF_GAS</code> exception.</p><h1 dir="auto"></h1>



a1-exp
<div class="markdown-heading" dir="auto">
<h2 class="heading-element" dir="auto" tabindex="-1">A1: EXP</h2><a aria-label="Permalink: A1: EXP" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a1-exp" id="user-content-a1-exp"></a>
</div><p dir="auto">Terms:</p><ul dir="auto">
<li><code>byte_len_exponent</code>: the number of bytes in the exponent (exponent is <code>b</code> in the stack
      representation)</li>
</ul><p dir="auto">Gas Calculation:</p><ul dir="auto">
<li><code>gas_cost = 10 + 50 * byte_len_exponent</code></li>
</ul>



a2-sha3
<div class="markdown-heading" dir="auto">
<h2 class="heading-element" dir="auto" tabindex="-1">A2: SHA3</h2><a aria-label="Permalink: A2: SHA3" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a2-sha3" id="user-content-a2-sha3"></a>
</div><p dir="auto">Terms:</p><ul dir="auto">
<li><code>data_size</code>: size of the message to hash in bytes (<code>len</code> in the stack representation)</li>
<li><code>data_size_words = (data_size + 31) // 32</code>: number of (32-byte) words in the message to hash</li>
<li><code>mem_expansion_cost</code>: the cost of any memory expansion required (see <a href="#a0-1-memory-expansion">A0-1</a>)</li>
</ul><p dir="auto">Gas Calculation:</p><ul dir="auto">
<li><code>gas_cost = 30 + 6 * data_size_words + mem_expansion_cost</code></li>
</ul>



a3-copy-operations
<div class="markdown-heading" dir="auto">
<h2 class="heading-element" dir="auto" tabindex="-1">A3: *COPY Operations</h2><a aria-label="Permalink: A3: *COPY Operations" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a3-copy-operations" id="user-content-a3-copy-operations"></a>
</div><p dir="auto">The following applies for the operations <code>CALLDATACOPY</code>, <code>CODECOPY</code>, and
    <code>RETURNDATACOPY</code> (not <code>EXTCODECOPY</code>).</p><p dir="auto">Terms:</p><ul dir="auto">
<li><code>data_size</code>: size of the data to copy in bytes (<code>len</code> in the stack representation)</li>
<li><code>data_size_words = (data_size + 31) // 32</code>: number of (32-byte) words in the data to copy</li>
<li><code>mem_expansion_cost</code>: the cost of any memory expansion required (see <a href="#a0-1-memory-expansion">A0-1</a>)</li>
</ul><p dir="auto">Gas Calculation:</p><ul dir="auto">
<li><code>gas_cost = 3 + 3 * data_size_words + mem_expansion_cost</code></li>
</ul>



a4-extcodecopy
<div class="markdown-heading" dir="auto">
<h2 class="heading-element" dir="auto" tabindex="-1">A4: EXTCODECOPY</h2><a aria-label="Permalink: A4: EXTCODECOPY" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a4-extcodecopy" id="user-content-a4-extcodecopy"></a>
</div><p dir="auto">Terms:</p><ul dir="auto">
<li><code>target_addr</code>: the address to copy code from (<code>addr</code> in the stack representation)</li>
<li><code>access_cost</code>: The cost of accessing a warm vs. cold account (see <a href="#a0-2-access-sets">A0-2</a>)
      <ul dir="auto">
<li><code>access_cost = 100</code> <strong>if</strong> <code>target_addr</code> <strong>in</strong>
<code>touched_addresses</code> (warm access)</li>
<li><code>access_cost = 2600</code> <strong>if</strong> <code>target_addr</code> <strong>not in</strong>
<code>touched_addresses</code> (cold access)</li>
</ul>
</li>
<li><code>data_size</code>: size of the data to copy in bytes (<code>len</code> in the stack representation)</li>
<li><code>data_size_words = (data_size + 31) // 32</code>: number of (32-byte) words in the data to copy</li>
<li><code>mem_expansion_cost</code>: the cost of any memory expansion required (see <a href="#a0-1-memory-expansion">A0-1</a>)</li>
</ul><p dir="auto">Gas Calculation:</p><ul dir="auto">
<li><code>gas_cost = access_cost + 3 * data_size_words + mem_expansion_cost</code></li>
</ul>



a5-balance-extcodesize-extcodehash
<div class="markdown-heading" dir="auto">
<h2 class="heading-element" dir="auto" tabindex="-1">A5: BALANCE, EXTCODESIZE, EXTCODEHASH</h2><a aria-label="Permalink: A5: BALANCE, EXTCODESIZE, EXTCODEHASH" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a5-balance-extcodesize-extcodehash" id="user-content-a5-balance-extcodesize-extcodehash"></a>
</div><p dir="auto">The opcodes <code>BALANCE</code>, <code>EXTCODESIZE</code>, <code>EXTCODEHASH</code> have the same
    pricing function based on making a single account access.
    See <a href="#a0-2-access-sets">A0-2</a> for details on EIP-2929 and <code>touched_addresses</code>.</p><p dir="auto">Terms:</p><ul dir="auto">
<li><code>target_addr</code>: the address of interest (<code>addr</code> in the opcode stack representations)</li>
</ul><p dir="auto">Gas Calculation:</p><ul dir="auto">
<li><code>gas_cost = 100</code> <strong>if</strong> <code>target_addr</code> <strong>in</strong>
<code>touched_addresses</code> (warm access)</li>
<li><code>gas_cost = 2600</code> <strong>if</strong> <code>target_addr</code> <strong>not in</strong>
<code>touched_addresses</code> (cold access)</li>
</ul>



a6-sload
<div class="markdown-heading" dir="auto">
<h2 class="heading-element" dir="auto" tabindex="-1">A6: SLOAD</h2><a aria-label="Permalink: A6: SLOAD" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a6-sload" id="user-content-a6-sload"></a>
</div><p dir="auto">See <a href="#a0-2-access-sets">A0-2</a> for details on EIP-2929 and <code>touched_storage_slots</code>.
  </p><p dir="auto">Terms:</p><ul dir="auto">
<li><code>context_addr</code>: the address of the current execution context (i.e. what <code>ADDRESS</code> would
      put on the stack)</li>
<li><code>target_storage_key</code>: The 32-byte storage index to load from (<code>key</code> in the stack
      representation)</li>
</ul><p dir="auto">Gas Calculation:</p><ul dir="auto">
<li><code>gas_cost = 100</code> <strong>if</strong> <code>(context_addr, target_storage_key)</code>
<strong>in</strong> <code>touched_storage_slots</code> (warm access)</li>
<li><code>gas_cost = 2100</code> <strong>if</strong> <code>(context_addr, target_storage_key)</code> <strong>not

In [8]:
gas = dup.copy()


def combine_gas(row):
    constant = row["Gas Constant"]
    dynamic = row["Gas Dynamic"]
    text = ""
    if not pd.isna(constant):
        text += str(constant)
    if not pd.isna(dynamic):
        if not pd.isna(constant):
            text += " + "
        text += "dynamic"
    return text


def fetch_dynamic(row):
    url = str(row["Gas Dynamic"])
    if url == "nan":
        return "<p>This opcode is not dynamic</p>"
    fragment = urlparse(url).fragment
    section = sections[fragment]["sections_pretty"]
    return section


gas.insert(
    gas.columns.get_loc("Mnemonic") + 1, "Gas", gas.apply(combine_gas, axis=1)
)

gas["Dynamic Gas Notes"] = gas.apply(fetch_dynamic, axis=1)
gas.insert(
    len(gas.columns),
    "Dynamic Gas Reference",
    gas["Gas Dynamic"].apply(
        lambda v: pd.NA if pd.isna(v) else f'<a href="{v}">{v}</a>'
    ),
)
gas.drop(columns=["Gas Constant", "Gas Dynamic"], inplace=True)
# gas.rename(columns={
#     "Gas Dynamic": "Gas Reference Url"
# }, inplace=True)


# gas
# with pd.option_context(*options):
#     display(gas)
display(gas)

,Opcode,Mnemonic,Gas,Inputs,Output,Mem / Storage,Notes,Dynamic Gas Notes,Dynamic Gas Reference
0,00,STOP,0,NaN,NaN,NaN,Halt execution,<p>This opcode is not dynamic</p>,NaN
1,01,ADD,3,"a, b",a + b,NaN,(u)int256 addition modulo 2**256,<p>This opcode is not dynamic</p>,NaN
2,02,MUL,5,"a, b",a * b,NaN,(u)int256 multiplication modulo 2**256,<p>This opcode is not dynamic</p>,NaN
3,03,SUB,3,"a, b",a - b,NaN,(u)int256 addition modulo 2**256,<p>This opcode is not dynamic</p>,NaN
4,04,DIV,5,"a, b",a // b,NaN,uint256 division,<p>This opcode is not dynamic</p>,NaN
...,...,...,...,...,...,...,...,...,...
90,FD,REVERT,dynamic,"ost, len",.,NaN,Revert(mem[ost:ost+len-1]),"<div class=""markdown-heading"" dir=""auto"">\n <h...","<a href=""https://github.com/wolflo/evm-opcodes..."
91,FE,INVALID,dynamic,NaN,NaN,NaN,Designated invalid opcode - EIP-141,"<div class=""markdown-heading"" dir=""auto"">\n <h...","<a href=""https://github.com/wolflo/evm-opcodes..."
92,FF,SELFDESTRUCT,dynamic,addr,.,NaN,Sends all ETH to addr; if executed in the same...,"<div class=""markdown-heading"" dir=""auto"">\n <h...","<a href=""https://github.com/wolflo/evm-opcodes..."
93,90..9F,SWAP[n],3,"a, ..., b","b, ..., a",NaN,swap top of the stack with the nth item,<p>This opcode is not dynamic</p>,<NA>
94,80..8F,DUP[n],3,"..., a","a, ..., a",NaN,clone nth value to the top of the stack,<p>This opcode is not dynamic</p>,<NA>

In [9]:
pretty = gas.copy()
for col in [
    "Inputs",
    "Output",
    "Mem / Storage",
    "Notes",
    "Dynamic Gas Reference",
]:
    pretty[col] = pretty[col].apply(lambda v: "None" if pd.isna(v) else v)
with pd.option_context(*options):
    display(pretty.head())

,Opcode,Mnemonic,Gas,Inputs,Output,Mem / Storage,Notes,Dynamic Gas Notes,Dynamic Gas Reference
0,00,STOP,0,None,None,None,Halt execution,<p>This opcode is not dynamic</p>,None
1,01,ADD,3,"a, b",a + b,None,(u)int256 addition modulo 2**256,<p>This opcode is not dynamic</p>,None
2,02,MUL,5,"a, b",a * b,None,(u)int256 multiplication modulo 2**256,<p>This opcode is not dynamic</p>,None
3,03,SUB,3,"a, b",a - b,None,(u)int256 addition modulo 2**256,<p>This opcode is not dynamic</p>,None
4,04,DIV,5,"a, b",a // b,None,uint256 division,<p>This opcode is not dynamic</p>,None

In [10]:
with pd.option_context(*options):
    display(print(pretty[pretty["Mnemonic"] == "SLOAD"]["Dynamic Gas Notes"]))

62    <div class="markdown-heading" dir="auto">\n <h2 class="heading-element" dir="auto" tabindex="-1">\n  A6: SLOAD\n </h2>\n <a aria-label="Permalink: A6: SLOAD" class="anchor" href="https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a6-sload" id="user-content-a6-sload">\n </a>\n</div>\n<p dir="auto">\n See\n <a href="#a0-2-access-sets">\n  A0-2\n </a>\n for details on EIP-2929 and\n <code>\n  touched_storage_slots\n </code>\n .\n</p>\n<p dir="auto">\n Terms:\n</p>\n<ul dir="auto">\n <li>\n  <code>\n   context_addr\n  </code>\n  : the address of the current execution context (i.e. what\n  <code>\n   ADDRESS\n  </code>\n  would\n      put on the stack)\n </li>\n <li>\n  <code>\n   target_storage_key\n  </code>\n  : The 32-byte storage index to load from (\n  <code>\n   key\n  </code>\n  in the stack\n      representation)\n </li>\n</ul>\n<p dir="auto">\n Gas Calculation:\n</p>\n<ul dir="auto">\n <li>\n  <code>\n   gas_cost = 100\n  </code>\n  <strong>\n   if\n  </strong>\n  <code>\n   (context_addr, target_storage_key)\n  </code>\n  <strong>\n   in\n  </strong>\n  <code>\n   touched_storage_slots\n  </code>\n  (warm access)\n </li>\n <li>\n  <code>\n   gas_cost = 2100\n  </code>\n  <strong>\n   if\n  </strong>\n  <code>\n   (context_addr, target_storage_key)\n  </code>\n  <strong>\n   not\n        in\n  </strong>\n  <code>\n   touched_storage_slots\n  </code>\n  (cold access)\n </li>\n</ul>\n
Name: Dynamic Gas Notes, dtype: object

None

In [12]:
pretty.to_csv(target_abspath, sep="|", index=False, header=False)